### ISSUE TITLE
[1.18][Bug]: Embur Bog and some other nether biomes arent generating.

### ISSUE THREAD

**Issue by WetSmellyFart** [CorgiTaco/BYG#1052]
### BYG Version

1.4.7

### Terrablender Version

1.2.0.126

### Mod Loader

Fabric

### Mod Loader Version

0.14.12

### Bug Severity

Major

### What happened?

For some reason Embur Bog just wont generate properly. Whenever I find a Embur Bog there's never any of the trees or ores that are supposed to spawn, it just looks like the normal nether with a yellow/orange atmosphere, I have tried everything from editing the NBT data to spawn it in, to deleting the byg config file, each and every time it doesn't load the Embur Bog properly. Please tell me what I'm doing wrong.

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/10300118/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Looks like your nether dimension is corrupted, try following the steps here to fix it: https://github.com/AOCAWOL/BYG/wiki/Nether-&-End-Biomes-FAQ

```[06:05:24] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:dimension_type]: [minecraft:minecraft_the_nether]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.class_7196.method_41900(class_7196.java:137) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java:57) ~[client-intermediary.jar:?]
```
