### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by KayyBabayy** [CorgiTaco/BYG#1077]
### BYG Version

1.19.2-2.0.0.13

### Terrablender Version

1.19.3-2.1.0.139

### Mod Loader

Forge

### Mod Loader Version

1.19.3-44.1.8

### What happened?

Honestly I am very new to minecraft on pc so I am not sure what I did wrong.

### crash-log

I do not know where to find this.

### latest.log

[28Jan2023 00:48:44.392] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, KayyBabayy, --version, 1.19.3-forge-44.1.8, --gameDir, C:\Users\yakim\AppData\Roaming\.minecraft\mods, --assetsDir, C:\Users\yakim\AppData\Roaming\.minecraft\assets, --assetIndex, 2, --uuid, 8d3cbf78cb2c4f59ac322172e1065964, --accessToken, ????????, --clientId, MmZlZjA1ZWItZDRjNy00NTkxLTllOGUtZGQ1NTc1ZDgwNjA4, --xuid, 2535461401567916, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 44.1.8, --fml.mcVersion, 1.19.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20221207.122022]
[28Jan2023 00:48:44.407] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[28Jan2023 00:48:45.550] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[28Jan2023 00:48:45.554] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/yakim/AppData/Roaming/.minecraft/mods/mods/OptiFine_1.19.3_HD_U_I2_pre2_MOD.jar%23189!/
[28Jan2023 00:48:45.562] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\yakim\AppData\Roaming\.minecraft\mods\mods\OptiFine_1.19.3_HD_U_I2_pre2_MOD.jar
[28Jan2023 00:48:45.577] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[28Jan2023 00:48:45.758] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/yakim/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2392!/ Service=ModLauncher Env=CLIENT
[28Jan2023 00:48:45.774] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[28Jan2023 00:48:47.005] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\yakim\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.3-44.1.8\fmlcore-1.19.3-44.1.8.jar is missing mods.toml file
[28Jan2023 00:48:47.012] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\yakim\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.3-44.1.8\javafmllanguage-1.19.3-44.1.8.jar is missing mods.toml file
[28Jan2023 00:48:47.025] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\yakim\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.3-44.1.8\lowcodelanguage-1.19.3-44.1.8.jar is missing mods.toml file
[28Jan2023 00:48:47.031] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\yakim\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.3-44.1.8\mclanguage-1.19.3-44.1.8.jar is missing mods.toml file
[28Jan2023 00:48:47.262] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection
[28Jan2023 00:48:48.264] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[28Jan2023 00:48:48.272] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 394
[28Jan2023 00:48:49.763] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[28Jan2023 00:48:51.199] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[28Jan2023 00:48:51.318] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.3-forge-44.1.8, --gameDir, C:\Users\yakim\AppData\Roaming\.minecraft\mods, --assetsDir, C:\Users\yakim\AppData\Roaming\.minecraft\assets, --uuid, 8d3cbf78cb2c4f59ac322172e1065964, --username, KayyBabayy, --assetIndex, 2, --accessToken, ????????, --clientId, MmZlZjA1ZWItZDRjNy00NTkxLTllOGUtZGQ1NTc1ZDgwNjA4, --xuid, 2535461401567916, --userType, msa, --versionType, release]
[28Jan2023 00:48:53.769] [main/WARN] [mixin/]: Error loading class: net/minecraft/data/loot/BlockLoot (java.lang.ClassNotFoundException: net.minecraft.data.loot.BlockLoot)
[28Jan2023 00:48:53.770] [main/WARN] [mixin/]: @Mixin target net.minecraft.data.loot.BlockLoot was not found moonlight-common.mixins.json:accessor.BlockLootAccessor
[28Jan2023 00:48:55.025] [main/WARN] [mixin/]: Error loading class: net/minecraft/data/advancements/AdventureAdvancements (java.lang.ClassNotFoundException: net.minecraft.data.advancements.AdventureAdvancements)
[28Jan2023 00:48:55.025] [main/WARN] [mixin/]: @Mixin target net.minecraft.data.advancements.AdventureAdvancements was not found byg.mixins.json:access.AdventureAdvancementsAccess
[28Jan2023 00:48:55.244] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/level/block/WoodButtonBlock (java.lang.ClassNotFoundException: net.minecraft.world.level.block.WoodButtonBlock)
[28Jan2023 00:48:55.244] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.level.block.WoodButtonBlock was not found byg.mixins.json:access.WoodButtonBlockAccess
[28Jan2023 00:48:56.039] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/Registry$RegistryBootstrap (java.lang.ClassNotFoundException: net.minecraft.core.Registry$RegistryBootstrap)
[28Jan2023 00:48:56.116] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/components/Button$OnTooltip (java.lang.ClassNotFoundException: net.minecraft.client.gui.components.Button$OnTooltip)
[28Jan2023 00:49:01.609] [main/FATAL] [mixin/]: Mixin apply failed byg_forge.mixins.json:client.MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method m_231380_ in byg_forge.mixins.json:client.MixinMinecraft was not located in the target class net.minecraft.client.Minecraft. Using refmap byg_forge.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method m_231380_ in byg_forge.mixins.json:client.MixinMinecraft was not located in the target class net.minecraft.client.Minecraft. Using refmap byg_forge.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:494) ~[OptiFine_1.19.3_HD_U_I2_pre2_MOD.jar%23240!/:?]
	at net.minecraft.CrashReport.m_127526_(CrashReport.java:175) ~[client-1.19.3-20221207.122022-srg.jar%23230!/:?]
	at net.minecraft.CrashReport.m_127529_(CrashReport.java:345) ~[client-1.19.3-20221207.122022-srg.jar%23230!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:144) ~[1.19.3-forge-44.1.8.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Not enough information in the log you sent to determine the cause. Delete your configs and try again
