### ISSUE TITLE
[1.19][Crash]: byg mod won't launch/load

### ISSUE THREAD

**Issue by icikiwir09** [CorgiTaco/BYG#1087]
### BYG Version

1.19.2

### Terrablender Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

1.19.2

### What happened?

hello! so my byg mod crashed and it won't launch/load. so when i play with byg mod on the previous the byg nothing wrong. and when i play byg mod on yesterday (17/2/2023) it won't launch for some reason. idrk what happen and i don't know how to. i don't know how to reset configs too. and this is what it says.

### crash-log

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-02-18 12:13:30
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.3-universal.jar%23158!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.3-universal.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

### latest.log

[12:12:36] [main/INFO]: ModLauncher running: args [--username, dark_beach23033, --version, ForgeOptiFine 1.19.2, --gameDir, C:\Users\dessy\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dessy\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 6fd7d36ce1f74a38b54c3474d21b1dde, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.3, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[12:12:36] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[12:12:36] [main/INFO]: OptiFineTransformationService.onLoad
[12:12:36] [main/INFO]: OptiFine ZIP file URL: union:/C:/Users/dessy/AppData/Roaming/.minecraft/mods/OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar%23149!/
[12:12:36] [main/INFO]: OptiFine ZIP file: C:\Users\dessy\AppData\Roaming\.minecraft\mods\OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar
[12:12:36] [main/INFO]: Target.PRE_CLASS is available
[12:12:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/dessy/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[12:12:36] [main/INFO]: OptiFineTransformationService.initialize
[12:12:37] [main/INFO]: Found mod file Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar of type MOD with provider {mods folder locator at C:\Users\dessy\AppData\Roaming\.minecraft\mods}
[12:12:37] [main/INFO]: Found mod file TerraBlender-forge-1.19.2-2.0.1.130.jar of type MOD with provider {mods folder locator at C:\Users\dessy\AppData\Roaming\.minecraft\mods}
[12:12:37] [main/INFO]: Found mod file tl_skin_cape_forge_1.19_1.19.2-1.28.jar of type MOD with provider {mods folder locator at C:\Users\dessy\AppData\Roaming\.minecraft\mods}
[12:12:37] [main/WARN]: Mod file C:\Users\dessy\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.3\fmlcore-1.19.2-43.2.3.jar is missing mods.toml file
[12:12:37] [main/WARN]: Mod file C:\Users\dessy\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.3\javafmllanguage-1.19.2-43.2.3.jar is missing mods.toml file
[12:12:37] [main/WARN]: Mod file C:\Users\dessy\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.3\lowcodelanguage-1.19.2-43.2.3.jar is missing mods.toml file
[12:12:37] [main/WARN]: Mod file C:\Users\dessy\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.3\mclanguage-1.19.2-43.2.3.jar is missing mods.toml file
[12:12:37] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.3.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: Found mod file forge-1.19.2-43.2.3-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2375b321
[12:12:37] [main/INFO]: No dependencies to load found. Skipping!
[12:12:38] [main/INFO]: OptiFineTransformationService.transformers
[12:12:38] [main/INFO]: Targets: 386
[12:12:38] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[12:12:39] [main/INFO]: Compatibility level set to JAVA_17
[12:12:39] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[12:12:39] [main/INFO]: Launching target 'forgeclient' with arguments [--version, ForgeOptiFine 1.19.2, --gameDir, C:\Users\dessy\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dessy\AppData\Roaming\.minecraft\assets, --uuid, 6fd7d36ce1f74a38b54c3474d21b1dde, --username, dark_beach23033, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, modified, --width, 925, --height, 530]
[12:12:46] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[12:12:50] [Render thread/WARN]: Assets URL 'union:/C:/Users/dessy/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23153!/assets/.mcassetsroot' uses unexpected schema
[12:12:50] [Render thread/WARN]: Assets URL 'union:/C:/Users/dessy/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23153!/data/.mcassetsroot' uses unexpected schema
[12:12:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:12:51] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.5.jar%23122!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.5.jar%23122!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.5.jar%23122!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.5.jar%23122!/:?]
	at net.minecraft.client.Minecraft.m_193585_(Minecraft.java:646) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:405) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.5.jar%23122!/:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.5.jar%23122!/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.5.jar%23122!/:?]
	... 19 more
[12:12:51] [Render thread/INFO]: Setting user: dark_beach23033
[12:12:51] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraft.launchwrapper.Launch
[12:12:51] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[12:12:51] [Render thread/INFO]: [OptiFine] 
[12:12:51] [Render thread/INFO]: [OptiFine] OptiFine_1.19.2_HD_U_I1_pre4
[12:12:51] [Render thread/INFO]: [OptiFine] Build: 20221114-000910
[12:12:51] [Render thread/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0
[12:12:51] [Render thread/INFO]: [OptiFine] Java: 17.0.3, Microsoft
[12:12:51] [Render thread/INFO]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
[12:12:51] [Render thread/INFO]: [OptiFine] LWJGL: 3.4.0 Win32 WGL Null EGL OSMesa VisualC DLL
[12:12:51] [Render thread/INFO]: [OptiFine] OpenGL: AMD Radeon(TM) RX Vega 11 Graphics, version 3.2.0 Core Profile Context 22.20.27.07.221020, ATI Technologies Inc.
[12:12:51] [Render thread/INFO]: [OptiFine] OpenGL Version: 3.2.0
[12:12:51] [Render thread/INFO]: [OptiFine] Maximum texture size: 16384x16384
[12:12:51] [VersionCheck/INFO]: [OptiFine] Checking for new version
[12:12:51] [Render thread/INFO]: [Shaders] OpenGL Version: 3.2.0 Core Profile Context 22.20.27.07.221020
[12:12:51] [Render thread/INFO]: [Shaders] Vendor:  ATI Technologies Inc.
[12:12:51] [Render thread/INFO]: [Shaders] Renderer: AMD Radeon(TM) RX Vega 11 Graphics
[12:12:51] [Render thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  - 
[12:12:51] [Render thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[12:12:51] [Render thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS: 8
[12:12:51] [Render thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[12:12:51] [Render thread/INFO]: [Shaders] Load shaders configuration.
[12:12:51] [Render thread/INFO]: [Shaders] No shaderpack loaded.
[12:12:51] [Render thread/INFO]: [OptiFine] [Shaders] Delayed loading of item mappings after resources are loaded
[12:12:51] [Render thread/INFO]: [OptiFine] [Shaders] Delayed loading of entity mappings after resources are loaded
[12:12:51] [modloading-worker-0/INFO]: Forge mod loading, version 43.2.3, for MC 1.19.2 with MCP 20220805.130853
[12:12:51] [modloading-worker-0/INFO]: MinecraftForge v43.2.3 Initialized
[12:12:52] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.19.2/HD_U.txt
[12:12:54] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: sun.misc.SharedSecrets
[12:12:54] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: jdk.internal.misc.SharedSecrets
[12:12:54] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: sun.misc.VM
[12:12:54] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.reflect.InaccessibleObjectException: Unable to make public static long jdk.internal.misc.VM.maxDirectMemory() accessible: module java.base does not "exports jdk.internal.misc" to module net.optifine
[12:12:55] [Worker-Main-1/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233789_(ProfileKeyPairManager.java:152) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_243396_(ProfileKeyPairManager.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[12:12:55] [Render thread/INFO]: Narrator library for x64 successfully loaded
[12:12:55] [Render thread/INFO]: Reloading ResourceManager: Mod Resources, FreshAnimations_v1.8.zip, Default, Simple+Grass+Flowers+v1.2.2.zip, xksp-v2-6-lush-plants.zip, XeKr+flowers+leaves+model+pack19plus1.1.zip, §bFallingLeaves§8-[v1.9.1].zip, xali's+Bushy+Leaves+v3.2.0.zip, Better+Leaves+Add-on+V2.9.1-1.19.zip, xali-s-Enchanted-Books-16x-v0.10.1.zip, xali's+Potions+v1.0.zip, Better_Farm_Animals_V2.zip, Better_Enderdragon.zip, Better_Dogs_V0.32.zip, Better_Cats_V0.05.zip, Dramatic+Skys+Demo+1.5.3.3.zip, Crosshair_TXF_1.19.zip, Fancy+Boss+Bars+v0.1.1.zip, VanillaTweaks_r748266.zip, Enhanced+Hud.zip, Brewing+Guide.zip, Torrezx-Fantasy_Illagers.zip, BvBOverlaysV4.zip
[12:12:56] [Render thread/INFO]: [OptiFine] *** Reloading textures ***
[12:12:56] [Render thread/INFO]: [OptiFine] Resource packs: Mod Resources, FreshAnimations_v1.8.zip, Simple+Grass+Flowers+v1.2.2.zip, xksp-v2-6-lush-plants.zip, XeKr+flowers+leaves+model+pack19plus1.1.zip, §bFallingLeaves§8-[v1.9.1].zip, xali's+Bushy+Leaves+v3.2.0.zip, Better+Leaves+Add-on+V2.9.1-1.19.zip, xali-s-Enchanted-Books-16x-v0.10.1.zip, xali's+Potions+v1.0.zip, Better_Farm_Animals_V2.zip, Better_Enderdragon.zip, Better_Dogs_V0.32.zip, Better_Cats_V0.05.zip, Dramatic+Skys+Demo+1.5.3.3.zip, Crosshair_TXF_1.19.zip, Fancy+Boss+Bars+v0.1.1.zip, VanillaTweaks_r748266.zip, Enhanced+Hud.zip, Brewing+Guide.zip, Torrezx-Fantasy_Illagers.zip, BvBOverlaysV4.zip
[12:12:56] [Render thread/WARN]: [OptiFine] Unknown resource pack file: mod_resources
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\end-biomes.json5" was read.
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\nether-biomes.json5" was read.
[12:12:56] [Render thread/INFO]: [OptiFine] RandomEntities: textures/entity/chicken.png, properties: optifine/mob/chicken.properties
[12:12:56] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[12:12:56] [Render thread/INFO]: [OptiFine] RandomEntities: textures/entity/cow/brown_mooshroom.png, variants: 2
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\overworld\byg-overworld-biomes.json5" was read.
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\surface_rules\end_surface_rules.json5" was read.
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\surface_rules\overworld_surface_rules.json5" was read.
[12:12:56] [Render thread/INFO]: [OptiFine] RandomEntities: textures/entity/cow/cow.png, variants: 10
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\surface_rules\nether_surface_rules.json5" was read.
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\growing-patterns.json5" was read.
[12:12:56] [Render thread/INFO]: [OptiFine] RandomEntities: textures/entity/cow/red_mooshroom.png, variants: 2
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\trades.json5" was read.
[12:12:56] [Render thread/INFO]: [OptiFine] RandomEntities: textures/entity/pig/pig.png, properties: optifine/mob/pig/pig.properties
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\settings.json5" was read.
[12:12:56] [Worker-Main-7/INFO]: "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\biomepedia.json5" was read.
[12:12:56] [Worker-Main-7/ERROR]: Exception caught during firing event: Config errors were found:

java.lang.IllegalArgumentException: Jankson file reading for "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\trades.json5" failed due to the following error(s):
java.lang.IllegalArgumentException: Jankson file reading for "C:\Users\dessy\AppData\Roaming\.minecraft\config\byg\trades.json5" failed due to the following error(s):
"morevillagers:woodworker" is not a valid id in registry: Registry[ResourceKey[minecraft:root / minecraft:villager_profession] (Experimental)].
Current Registry Values:

### Did you isolate BYG?

I tried BYG alone

**Comment by icikiwir09** [comment]
update : i got it fix yay

**Comment by Calico-OS** [comment]
Hi! What did you do to fix the issue?

**Comment by SuperStormer** [comment]
To anyone else that runs into the same issue: delete `config/byg/trades.json5`.
