### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by EnbyBro** [CorgiTaco/BYG#1093]
### BYG Version

2.0.0.2

### Terrablender Version

2.0.1.130

### Mod Loader

Fabric

### Mod Loader Version

1.19.2

### What happened?

I get to the world creation screen and my game immediately crashes.

### crash-log

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-02-25 14:02:17
Description: Starting integrated server

java.lang.IllegalArgumentException: "byg:windswept_beach" is not a valid biome in the world registry!
	at potionstudios.byg.world.biome.BYGTerraBlenderRegion.lambda$addBiomes$2(BYGTerraBlenderRegion.java:96)
	at net.minecraft.class_6554.method_38187(class_6554.java:583)
	at net.minecraft.class_6554.method_38196(class_6554.java:386)
	at net.minecraft.class_6554.method_38195(class_6554.java:239)
	at net.minecraft.class_6554.method_38185(class_6554.java:206)
	at net.minecraft.class_6554.byg_invokeAddBiomes(class_6554.java)
	at potionstudios.byg.world.biome.BYGTerraBlenderRegion.addBiomes(BYGTerraBlenderRegion.java:93)
	at terrablender.worldgen.noise.InitialLayer.lambda$new$1(InitialLayer.java:45)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at terrablender.worldgen.noise.InitialLayer.<init>(InitialLayer.java:49)
	at terrablender.worldgen.noise.LayeredNoiseUtil.uniqueness(LayeredNoiseUtil.java:36)
	at net.minecraft.class_6544$class_6547.initializeForTerraBlender(class_6544.java:561)
	at terrablender.util.LevelUtils.initializeBiomes(LevelUtils.java:108)
	at terrablender.util.LevelUtils.initializeOnServerStart(LevelUtils.java:57)
	at net.minecraft.server.MinecraftServer.handler$ekl001$onInit(MinecraftServer.java:2270)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:295)
	at net.minecraft.class_1132.<init>(class_1132.java:49)
	at net.minecraft.class_310.method_29603(class_310.java:2045)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264)
	at net.minecraft.class_310.method_29610(class_310.java:2045)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at potionstudios.byg.world.biome.BYGTerraBlenderRegion.lambda$addBiomes$2(BYGTerraBlenderRegion.java:96)
	at net.minecraft.class_6554.method_38187(class_6554.java:583)
	at net.minecraft.class_6554.method_38196(class_6554.java:386)
	at net.minecraft.class_6554.method_38195(class_6554.java:239)
	at net.minecraft.class_6554.method_38185(class_6554.java:206)
	at net.minecraft.class_6554.byg_invokeAddBiomes(class_6554.java)
	at potionstudios.byg.world.biome.BYGTerraBlenderRegion.addBiomes(BYGTerraBlenderRegion.java:93)
	at terrablender.worldgen.noise.InitialLayer.lambda$new$1(InitialLayer.java:45)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at terrablender.worldgen.noise.InitialLayer.<init>(InitialLayer.java:49)
	at terrablender.worldgen.noise.LayeredNoiseUtil.uniqueness(LayeredNoiseUtil.java:36)
	at net.minecraft.class_6544$class_6547.initializeForTerraBlender(class_6544.java:561)
	at terrablender.util.LevelUtils.initializeBiomes(LevelUtils.java:108)
	at terrablender.util.LevelUtils.initializeOnServerStart(LevelUtils.java:57)
	at net.minecraft.server.MinecraftServer.handler$ekl001$onInit(MinecraftServer.java:2270)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:295)
	at net.minecraft.class_1132.<init>(class_1132.java:49)
	at net.minecraft.class_310.method_29603(class_310.java:2045)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264)
	at net.minecraft.class_310.method_29610(class_310.java:2045)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2045)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_525
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, walllanterns/moddedlanternscompat
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 134871976 bytes (128 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12450H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a3
	Graphics card #0 versionInfo: DriverVersion=30.0.101.2079
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f9d
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1339
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18100.13
	Virtual memory used (MB): 11653.29
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 615.81
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alloy_forgery: Alloy Forgery 2.0.19+1.19
		amethyst_core: Amethyst Core 1.0.4+1.19
		amethyst_imbuement: Amethyst Imbuement 1.19-28
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
			structurized-reborn: Structurized Reborn 1.19-01
		architectury: Architectury 6.5.69
		archon: Archon 0.4.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		betternether: Better Nether 7.1.3
		bewitchment: Bewitchment 1.19-6
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.8.0
			midnightlib: MidnightLib 0.6.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		bookshelf: Bookshelf 16.2.17
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.5-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botania: Botania 1.19.2-437-FABRIC
			fiber: fiber 0.23.0-2
		botanypots: BotanyPots 9.0.27
		bushierflowers: Bushier Flowers 0.0.1-1.19.2
		bwplus: Bewitchment Plus 1.19-9
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		chimes: Chimes 1.1.4
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.0.3+1.19.2
			spectrelib: SpectreLib 0.10.0+1.19
		cosmetic-armor: Cosmetic Armor 1.4.0
		creeperoverhaul: Creeper Overhaul 2.0.7
		crittersandcompanions: Critters and Companions 1.19.2-1.0.3
		dataattributes: Data Attributes 1.2.8
		decorative_blocks: Decorative Blocks 3.0.0
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.4.1
		dungeons_arise: When Dungeons Arise 2.1.54
		easymagic: Easy Magic 4.3.2
		elementary-staffs: Elementary Staffs 2.0.0
		extraalchemy: Extra Alchemy 1.9.0
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.14
		forgeconfigapiport: Forge Config API Port 4.2.11
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		fzzy_core: Fzzy Core 0.1.2+1.19
		geckolib3: Geckolib 3.1.39
			com_eliotlash_mclib_mclib: mclib 20
		gobber2: Gobber2 2.6.61
			pugh_lib: Pugh Lib 1.4.15
			pugh_tools: Pugh Tools 1.3.23
		goodall: Goodall 1.2.0
		handcrafted: Handcrafted 2.0.2
		hexcasting: Hex Casting 0.10.3
			serialization_hooks: Serialization Hooks 0.3.24
		indypets: IndyPets - Independent Pets 1.1.0-1.19.2
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.10.4
		magiccombatwands: Magic Combat Wands 1.0.2
		majobroom: Majo's Broom 1.2.2
		mcwbridges: Macaw's Bridges 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.2
		mcwwindows: Macaw's Windows 2.1.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		mythicmetals: Mythic Metals 0.17.2+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
		mythicmetals_decorations: Mythic Metals Decorations 0.5.2+1.19.2
		mythicmounts: Mythic Mounts 1.19.2-7.1
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				calio: Calio 1.7.0
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-77-FABRIC
		paucal: PAUCAL 0.5.0
		pehkui: Pehkui 3.5.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		playerabilitylib: Pal 1.6.0
		plushies: Plushie Mod 1.2
		puzzleslib: Puzzles Lib 4.3.12
		roughlyenoughitems: Roughly Enough Items 9.1.591
			error_notifier: Error Notifier 1.0.9
		sod: Sod 22.10.13
		spirit: Spirit 2.2.3
			resourcefullib: Resourceful Lib 1.1.12
		t_and_t: Towns and Towers 1.10
		taterzens: Taterzens 1.11.1
			config2brigadier: Config to Brigadier 1.2.1
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.3+1.19.1
		terrablender: TerraBlender 2.0.1.130
		tradernpcs: Trader NPCs 1.2.0
		trinkets: Trinkets 3.4.2
		walllanterns: Lanterns Belong on Walls 1.4.0-1.19
		xaerominimap: Xaero's Minimap 23.1.0
		z_mcwfencesbyg: Macaw's Fences - BYG 1.19.2-1.0
		z_mcwroofsbyg: Macaw's Roofs - BYG 1.19.2-1.1
	Launched Version: fabric-loader-0.14.14-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 513.39, NVIDIA Corporation
	Window size: 1920x1051
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12450H

### latest.log

[2023-02-11-1.log.gz](https://github.com/AOCAWOL/BYG/files/10834717/2023-02-11-1.log.gz)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Reset your configs
