### ISSUE TITLE
[1.19][Bug]: Growing saplings crash game

### ISSUE THREAD

**Issue by Greg-J** [CorgiTaco/BYG#1097]
### BYG Version

2.0.1.0

### Terrablender Version

2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

14.14-1.19.2

### Bug Severity

Major

### What happened?

Planted Willow and Brown Zelkova saplings and experienced a crash seemingly when the Willow saplings were random ticked. For what it's worth, the Willow saplings were placed incorrectly by me and were not in the 5x5 layout that they should have been in.

### latest.log

`[11:09:41] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bpb000$modifiedRunLoop(MinecraftServer.java:6385) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because the return value of "net.minecraft.class_2378.method_10221(Object)" is null
	at potionstudios.byg.util.BYGUtil.dumpRegistry(BYGUtil.java:74) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0.jar:?]
	at potionstudios.byg.util.FeatureGrowerFromBlockPattern.growFeature(FeatureGrowerFromBlockPattern.java:150) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0.jar:?]
	at potionstudios.byg.common.block.sapling.BYGSaplingBlock.method_10507(BYGSaplingBlock.java:46) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0.jar:?]
	at net.minecraft.class_2473.method_9514(class_2473.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:948) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.redirect$ggf000$redirectBlockStateTick(class_3218.java:22732) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18203(class_3218.java:496) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:319) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[client-intermediary.jar:?]
	... 6 more

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
Should not be possible for this throw the exception it did, it's like the block doesn't exist. I can't recreate this myself so I'm going to assume this is a mod conflict of some kind. 


Could you try BYG alone? And if that works but it doesn't work in your modpack, could you send your entire latest.log and make an attempt to narrow down the conflicting mod?

**Comment by Kex1016** [comment]
Hey! I think I found something, if I have the [Colorful Azaleas](https://modrinth.com/mod/colorful-azaleas) mod in my server, it crashes with this error. I haven't done more testing, but this seemed to be the issue for my server because when I disabled the mod it stopped crashing.

**Comment by SennytheSnek** [comment]
I can confirm this bug, it also happens on 1.19.2 Forge when running both Biomes You'll Go and Colorful Azaleas
[crash-2023-06-07_12.31.20-server.txt](https://github.com/AOCAWOL/BYG/files/11676212/crash-2023-06-07_12.31.20-server.txt)
[crash-2023-06-07_12.40.13-server.txt](https://github.com/AOCAWOL/BYG/files/11676216/crash-2023-06-07_12.40.13-server.txt)
[crash-2023-06-07_13.19.13-server.txt](https://github.com/AOCAWOL/BYG/files/11676219/crash-2023-06-07_13.19.13-server.txt)
Disabling Colorful Azaleas fixed it
Edit: After further testing, my friend's modpack appears to be corrupted beyond belief by something else
Isolating BYG and CA together did not result in a crash or any sort of error
The tree grew completely fine
I'm gonna try to figure out what is happening to my friend's modpack
Edit 2: Manually deleting and reinstalling BYG, Terrablender, [Geckolib](https://www.curseforge.com/minecraft/mc-mods/geckolib), as well as deleting [CorgiLib](https://www.curseforge.com/minecraft/mc-mods/corgilib) and resetting BYG configs seems to have fixed it
Colorful Azaleas is also completely fine
I still don't know what the problem was, but I have the original zip file with the corrupted modpack if anyone wants to tinker with it
(Just an FYI, resetting BYG configs on their own did not fix the issue)

**Comment by CorgiTaco** [comment]
Closing this as @SennytheSnek found the possible solution, and no response from @Greg-J.
