### ISSUE TITLE
[1.19.2] Crash with William Wythers' Overhauled Overworld

### ISSUE THREAD

**Issue by dmkenza** [CorgiTaco/BYG#1110]
### BYG Version

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0

### Terrablender Version

TerraBlender-fabric-1.19.2-2.0.1.136

### Mod Loader

Fabric

### Mod Loader Version

0.14.17

### What happened?

The crush on  world generating when i used BYG with William Wythers' Overhauled Overworld.

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0
causes the problem for now.

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7
The previous one dosnt cause.

### crash-log

Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 9
Feature 'minecraft:patch_grass_savanna'
must be before 'minecraft:patch_grass_taiga_2' (defined in 'byg:maple_taiga' at index 2, 3)
must be before 'minecraft:brown_mushroom_taiga' (defined in 'byg:shattered_glacier' at index 3, 4 and 8 others)
must be before 'minecraft:red_mushroom_taiga' (defined in 'minecraft:mushroom_fields' at index 2, 3 and 14 others)
must be before 'minecraft:patch_grass_savanna' (defined in 'wythers:cold_island' at index 4, 5)

at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141)
at net.minecraft.class_7510.handler$bmf000$buildFeaturesPerStepWithAdvancedCycleDetection(class_7510.java:529)
at net.minecraft.class_7510.method_44210(class_7510.java)
at net.minecraft.class_2794.method_44215(class_2794.java:136)
at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
at net.minecraft.class_2794.method_12102(class_2794.java:397)
at net.minecraft.class_2806.method_20613(class_2806.java:145)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:679)
... 14 more

### latest.log

Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 9
Feature 'minecraft:patch_grass_savanna'
must be before 'minecraft:patch_grass_taiga_2' (defined in 'byg:maple_taiga' at index 2, 3)
must be before 'minecraft:brown_mushroom_taiga' (defined in 'byg:shattered_glacier' at index 3, 4 and 8 others)
must be before 'minecraft:red_mushroom_taiga' (defined in 'minecraft:mushroom_fields' at index 2, 3 and 14 others)
must be before 'minecraft:patch_grass_savanna' (defined in 'wythers:cold_island' at index 4, 5)

at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141)
at net.minecraft.class_7510.handler$bmf000$buildFeaturesPerStepWithAdvancedCycleDetection(class_7510.java:529)
at net.minecraft.class_7510.method_44210(class_7510.java)
at net.minecraft.class_2794.method_44215(class_2794.java:136)
at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
at net.minecraft.class_2794.method_12102(class_2794.java:397)
at net.minecraft.class_2806.method_20613(class_2806.java:145)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:679)
... 14 more

### Did you isolate BYG?

I tried BYG alone

**Comment by enmumne** [comment]
Related and probably already fixed: https://github.com/AOCAWOL/BYG/issues/1101

We are all waiting for a new version.

**Comment by CorgiTaco** [comment]
Can't recreate a crash, so should be fixed on latest!
