### ISSUE TITLE
[1.19][Crash]: Isn't starting Forge 43.2.8

### ISSUE THREAD

**Issue by Minelsgo** [CorgiTaco/BYG#1128]
### BYG Version

2.0.1.1

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.2.8

### What happened?

Isn't starting

I created an Instance with only Byg, TerraBlender and Corgi Lib

Doesn't work on my server too

### crash-log

Didn't start, so I don't have a crash log

### latest.log

Prism Launcher version: 6.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.64.91.47, 18.64.91.58, 18.64.91.44, 18.64.91.36]

session.minecraft.net resolves to:
    [2620:1ec:4f:1::45, 2620:1ec:4e:1::45, 13.107.237.45, 13.107.238.45]

textures.minecraft.net resolves to:
    [2620:1ec:4f:1::45, 2620:1ec:4e:1::45, 13.107.237.45, 13.107.238.45]

api.mojang.com resolves to:
    [2620:1ec:4e:1::45, 2620:1ec:4f:1::45, 13.107.237.45, 13.107.238.45]

Minecraft folder is:
/home/minelsgo/.local/share/PrismLauncher/instances/bygt/.minecraft

Java path is:
/usr/lib/jvm/java-17-oracle/bin/java

Checking Java version...
Java is version 17.0.5, using 64 (amd64) architecture, from Oracle Corporation.

AMD Ryzen 5 3600X 6-Core Processor
NVIDIA Corporation TU116 [GeForce GTX 1660 SUPER] (rev a1)

Subsystem: Gigabyte Technology Co., Ltd TU116 [GeForce GTX 1660 SUPER]

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 525.89.02

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /home/minelsgo/.local/share/PrismLauncher/instances/bygt/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.1/lwjgl-glfw-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-x86_64.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-aarch_64.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/text2speech-natives-linux/1.13.9/text2speech-natives-linux-1.13.9.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.19.2-43.2.8/fmlloader-1.19.2-43.2.8.jar
  /home/minelsgo/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:

Mods:
  [✔] CorgiLib-forge-1.19.2-1.0.0.32
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1
  [✔] TerraBlender-forge-1.19.2-2.0.1.136

Params:
  --username  --version 1.19.2 --gameDir /home/minelsgo/.local/share/PrismLauncher/instances/bygt/.minecraft --assetsDir /home/minelsgo/.local/share/PrismLauncher/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 43.2.8 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 89569

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-03-25 15:13:28,626 main WARN Advanced terminal features are not available in this environment
[15:13:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, MinelsGO, --version, 1.19.2, --gameDir, /home/minelsgo/.local/share/PrismLauncher/instances/bygt/.minecraft, --assetsDir, /home/minelsgo/.local/share/PrismLauncher/assets, --assetIndex, 1.19, --uuid, <PROFILE ID>, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.8, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[15:13:28] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.5 by Oracle Corporation; OS Linux arch amd64 version 6.2.6-76060206-generic
[15:13:28] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/minelsgo/.local/share/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23138!/ Service=ModLauncher Env=CLIENT
[15:13:28] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Configuration file /home/minelsgo/.local/share/PrismLauncher/instances/bygt/.minecraft/config/fml.toml is not correct. Correcting
[15:13:28] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[15:13:29] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/fmlcore/1.19.2-43.2.8/fmlcore-1.19.2-43.2.8.jar is missing mods.toml file
[15:13:29] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.2.8/javafmllanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:13:29] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.2.8/lowcodelanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:13:29] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/minelsgo/.local/share/PrismLauncher/libraries/net/minecraftforge/mclanguage/1.19.2-43.2.8/mclanguage-1.19.2-43.2.8.jar is missing mods.toml file
[15:13:29] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[15:13:29] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[15:13:29] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2, --gameDir, /home/minelsgo/.local/share/PrismLauncher/instances/bygt/.minecraft, --assetsDir, /home/minelsgo/.local/share/PrismLauncher/assets, --uuid, <PROFILE ID>, --username, MinelsGO, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --width, 854, --height, 480]
[15:13:29] [main/WARN] [mixin/]: Reference map '${refmap_target}refmap.json' for corgilib.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[15:13:32] [pool-3-thread-1/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.8/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: software/bernie/geckolib3/core/IAnimatable
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.8/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:145)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	... 21 more
Caused by: java.lang.NoClassDefFoundError: software/bernie/geckolib3/core/IAnimatable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:262)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:665)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.lambda$run$0(Main.java:145)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: software.bernie.geckolib3.core.IAnimatable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 more
Exiting with ERROR
Process exited with code 2.

### Did you isolate BYG?

I tried BYG alone

**Comment by ghost** [comment]
Can confirm the issue is happening on my end as well.

**Comment by Aleon4201** [comment]
At the first, what mods does BYG require?
Even CorgiLib isn't shown on error screen in-game, that causes launch crash without crash log.
Moreover, only TerraBlender is in Relation page of CurseForge, but CorgiLib isn't.
Please show us what are required for using BYG on the top or Relation page in CurseForge, developers. Modern CurseForge doesn't have Related mods lists on the bottom in any file page.

P.S. players need GeckoLib too.

**Comment by CorgiTaco** [comment]
You needd geckolib
