### ISSUE TITLE
[1.19][Crash]: 

### ISSUE THREAD

**Issue by Pantheris2019** [CorgiTaco/BYG#1284]
### BYG Version

2.0.1.5

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.3.0

### What happened?

The growing sapling each time it ticks is crashing the server instead of growing into a tree.

Isolating BYG is not necessary as the stacktrace points directly at BYG as the issue as you will find in the crashlog.

### crash-log
Here is the text file which is taken from the crash log
[message.txt](https://github.com/AOCAWOL/BYG/files/13258226/message.txt)

### latest.log

I do not have access to this.

### Did you isolate BYG?

I did not try BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by Pantheris2019** [comment]
I will snippet the exact portion of the stacktrace which points to the sapling from BYG being the problem.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.grower.AbstractTreeGrower.m_213817_(net.minecraft.server.level.ServerLevel, net.minecraft.world.level.chunk.ChunkGenerator, net.minecraft.core.BlockPos, net.minecraft.world.level.block.state.BlockState, net.minecraft.util.RandomSource)" because "this.f_55975_" is null
	at net.minecraft.world.level.block.SaplingBlock.m_222000_(SaplingBlock.java:45) ~[server-1.19.2-20220805.130853-srg.jar%23459!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.block.SaplingBlockMixin,pl:mixin:A}
	at potionstudios.byg.common.block.sapling.BYGSaplingBlock.m_222000_(BYGSaplingBlock.java:48) ~[Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.5.jar%23403!/:2.0.1.5] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.m_213898_(SaplingBlock.java:36) ~[server-1.19.2-20220805.130853-srg.jar%23459!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.block.SaplingBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[server-1.19.2-20220805.130853-srg.jar%23459!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23459!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}`

**Comment by JT122406** [comment]
fixed in #1283

**Comment by Pantheris2019** [comment]
Thank you.
