### ISSUE TITLE
[1.19][Bug]: Creative inventory crash

### ISSUE THREAD

**Issue by Orangejewce92** [CorgiTaco/BYG#1305]
### BYG Version

2.0.1.6

### Terrablender Version

2.0.1.136

### Mod Loader

Forge

### Mod Loader Version

43.3.8

### Bug Severity

Minor

### What happened?

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Registry Object not present: bygonenether:withered_debris

Withered debris is crashing my game when i go into the creative tab :)

### latest.log

[01Mar2024 17:22:08.803] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[01Mar2024 17:22:09.543] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.8.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Registry Object not present: bygonenether:withered_debris
	at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.3.8-universal.jar%23762!/:?]
	at com.izofar.bygonenether.init.ModCreativeModeTabs$1.m_6976_(ModCreativeModeTabs.java:11) ~[bygonenether-1.3.2-1.19.2.jar%23500!/:1.3.2]
	at net.minecraft.world.item.CreativeModeTab.m_40787_(CreativeModeTab.java:120) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_98581_(CreativeModeInventoryScreen.java:803) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_7286_(CreativeModeInventoryScreen.java:689) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_6305_(EffectRenderingInventoryScreen.java:28) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:605) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.3.8-universal.jar%23762!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.3.8-universal.jar%23762!/:?]
	at net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$254(GameRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.renderer.GameRenderer.wrapOperation$fdd000$wrapRenderScreenFancyMenu(GameRenderer.java:8562) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?]

### Did you isolate BYG?

I tried BYG alone

### Did you read and understand the above agreement?

- [X] I agree.

**Comment by JT122406** [comment]
this is from bygonenether mod and not byg

**Comment by Orangejewce92** [comment]
Ah! My bad thanks for the clarification
