### ISSUE TITLE
Minecraft crashes when loading modpack

### ISSUE THREAD

**Issue by sunias** [CorgiTaco/BYG#165]
These are the mods:
![image](https://user-images.githubusercontent.com/74004670/98582180-e3749400-22c2-11eb-92d9-40064d1c5cdc.png)
this is the minecraft crash message:
![image](https://user-images.githubusercontent.com/74004670/98582231-f5eecd80-22c2-11eb-9534-80ad4ffbbc35.png)
and here the crash log:
---- Minecraft Crash Report ----
// My bad.

Time: 09.11.20 19:33
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5033/811545119.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4624/1382034504.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$487/1570022108.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130) ~[?:1.1.2] {re:classloading}
-- MOD byg --
Details:
	Mod File: byg-1.1.2.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.1.1
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130) ~[?:1.1.2] {re:classloading}
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:16) ~[?:1.1.2] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGBiomesJSONConfig(BYGJsonConfigHandler.java:36) ~[?:1.1.2] {re:classloading}
	at corgiaoc.byg.BYG.commonSetup(BYG.java:82) ~[?:1.1.2] {re:classloading}
	at corgiaoc.byg.BYG$$Lambda$3314/169980323.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2905/306482657.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3097/92221031.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3522815128 bytes (3359 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G5%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.42-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |SIDED_SETU|NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2 (3).jar                 |Mouse Tweaks                  |mousetweaks                   |2.13                |SIDED_SETU|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |SIDED_SETU|NOSIGNATURE
		jei-1.16.4-7.6.0.53 (1).jar                       |Just Enough Items             |jei                           |7.6.0.53            |SIDED_SETU|NOSIGNATURE
		goblintraders-1.2.2-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.2.2               |SIDED_SETU|NOSIGNATURE
		car-1.16.3-1.0.4.jar                              |Ultimate Car Mod              |car                           |1.16.3-1.0.4        |SIDED_SETU|NOSIGNATURE
		Neat+1.7-24.jar                                   |Neat                          |neat                          |1.7-24              |SIDED_SETU|NOSIGNATURE
		BetterCaves-1.16.2-1.0.4 (4).jar                  |YUNG's Better Caves           |bettercaves                   |1.16.2-1.0.4        |SIDED_SETU|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |SIDED_SETU|NOSIGNATURE
		Clumps-6.0.0.12 (1).jar                           |Clumps                        |clumps                        |6.0.0.12            |SIDED_SETU|NOSIGNATURE
		betterweather-1.0.3 (1).jar                       |Better Weather                |betterweather                 |1.0.1               |SIDED_SETU|NOSIGNATURE
		FastWorkbench-1.16.3-4.4.0 (1).jar                |FastWorkbench                 |fastbench                     |4.4.0               |SIDED_SETU|NOSIGNATURE
		Placebo-1.16.3-4.3.3 (1).jar                      |Placebo                       |placebo                       |4.3.3               |SIDED_SETU|NOSIGNATURE
		ftb-ultimine-1603.1.1.12 (2).jar                  |FTB Ultimine                  |ftbultimine                   |1603.1.1.12         |SIDED_SETU|NOSIGNATURE
		DungeonCrawl-1.16.3-2.1.1.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.1.1               |SIDED_SETU|NOSIGNATURE
		Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar           |Wither Skeleton Tweaks        |wstweaks                      |5.2.1               |SIDED_SETU|NOSIGNATURE
		randompatches-1.16.2-1.22.1.2.jar                 |RandomPatches                 |randompatches                 |1.16.2-1.22.1.2     |SIDED_SETU|92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		FastFurnace-1.16.3-4.3.0 (1).jar                  |FastFurnace                   |fastfurnace                   |4.3.0               |SIDED_SETU|NOSIGNATURE
		ironshulkerboxes-1.16.4-5.1.9.jar                 |Iron Shulker Boxes            |ironshulkerbox                |1.16.4-5.1.9        |SIDED_SETU|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |SIDED_SETU|NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2 (3).jar            |Waila                         |waila                         |1.10.11-B78_1.16.2  |SIDED_SETU|NOSIGNATURE
		byg-1.1.2.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.1               |ERROR     |NOSIGNATURE
		forgemod_VoxelMap-1.10.11_for_1.16.3 (1).jar      |VoxelMap                      |voxelmap                      |1.10.11             |SIDED_SETU|NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.3-0.8.9.jar                          |Waddles                       |waddles                       |1.16.3-0.8.9        |SIDED_SETU|NOSIGNATURE
		Aquaculture-1.16.4-2.1.6 (1).jar                  |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.6        |SIDED_SETU|NOSIGNATURE
		speedyladders-1.16.3-1.jar                        |Speedy Ladders                |speedyladders                 |1.16.3-1            |SIDED_SETU|NOSIGNATURE
		CosmeticArmorReworked-1.16.4-v1.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.4-v1           |SIDED_SETU|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: e3cbe120-95f5-429c-be8d-9822c6db3923
	OptiFine Version: OptiFine_1.16.3_HD_U_G5
	OptiFine Build: 20201106-202857
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.09
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by CorgiTaco** [comment]
Delete your config and let it regenerate. Uninstall optifine aswell bc they're known to cause issues.
