### ISSUE TITLE
Encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Kyuketsuki147** [CorgiTaco/BYG#205]
I am running minecraft version 1.16.4, and BYG 1.1.
I have never run this mod before but it looked good so wanted to try it. I have used plenty of mods before so i dont belive i am messing up with the installation. I had multiple mods installed upon initial installation and so at first thought it may be a mod conflict. i usually find adding mods one by one with the new install is the easiest way to fix this so i have removed all other mods and was going to start to add them in but i cant get to load on its own. I have tried installing this 3 times removing and redownloading, i got the fabric version to work but as all my mods are forge so would like to use this version if possible.

__**API/Modloader**__
Forge

__**Describe the bug**__
Minecraft will not load up with mod installed

**Logs**

Crashlog ---- Minecraft Crash Report ----
// There are four lights!

Time: 18/12/20 18:53
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4056/442705507.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3753/1441225952.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$471/2097361633.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130) ~[?:1.1.5] {re:classloading}
-- MOD byg --
Details:
	Mod File: byg-1.1.5.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.1.5
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130) ~[?:1.1.5] {re:classloading}
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:16) ~[?:1.1.5] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGBiomesJSONConfig(BYGJsonConfigHandler.java:36) ~[?:1.1.5] {re:classloading}
	at corgiaoc.byg.BYG.commonSetup(BYG.java:77) ~[?:1.1.5] {re:classloading}
	at corgiaoc.byg.BYG$$Lambda$3108/1233602635.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2912/1892470159.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3080/215690645.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 735161864 bytes (701 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |SIDED_SETU|NOSIGNATURE
		byg-1.1.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.5               |ERROR     |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 6f8287c6-3321-43d9-b41f-2ae18af74e44

Latest.log - 
[18Dec2020 19:00:47.571] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Kyuketsuki147, --version, 1.16.4-forge-35.1.13, --gameDir, C:\Users\dinny\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dinny\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, a409aa41ab64425dad4a04380f52708c, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.13, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[18Dec2020 19:00:47.575] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_51 by Oracle Corporation
[18Dec2020 19:00:47.593] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[18Dec2020 19:00:47.929] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[18Dec2020 19:00:47.989] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/dinny/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[18Dec2020 19:00:50.496] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [corgiaoc.byg.mixin.MixinConnector]
[18Dec2020 19:00:50.503] [main/INFO] [corgiaoc.byg.BYG/]: BYG: Mixin Connected!
[18Dec2020 19:00:50.503] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.4-forge-35.1.13, --gameDir, C:\Users\dinny\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dinny\AppData\Roaming\.minecraft\assets, --uuid, a409aa41ab64425dad4a04380f52708c, --username, Kyuketsuki147, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release]
[18Dec2020 19:01:00.579] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18Dec2020 19:01:01.580] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Kyuketsuki147
[18Dec2020 19:01:01.766] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[18Dec2020 19:01:03.164] [modloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 35.1.13, for MC 1.16.4 with MCP 20201102.104115
[18Dec2020 19:01:03.165] [modloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v35.1.13 Initialized
[18Dec2020 19:01:03.257] [modloading-worker-1/INFO] [corgiaoc.byg.BYG/]: Loading config: C:\Users\dinny\AppData\Roaming\.minecraft\config\byg\byg-world.toml
[18Dec2020 19:01:06.327] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Blocks registered!
[18Dec2020 19:01:06.531] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Items registered!
[18Dec2020 19:01:06.651] [Render thread/ERROR] [net.minecraft.util.Util/]: No data fixer registered for byg:boat
[18Dec2020 19:01:06.653] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Entities registered!
[18Dec2020 19:01:09.125] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Biomes registered!
[18Dec2020 19:01:09.141] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Decorators registered!
[18Dec2020 19:01:09.143] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Features registered!
[18Dec2020 19:01:09.147] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Structures registered!
[18Dec2020 19:01:09.149] [Render thread/INFO] [corgiaoc.byg.BYG/]: BYG: Surface builders Registered!
[18Dec2020 19:01:10.840] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[18Dec2020 19:01:10.917] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Mod Resources, Default
[18Dec2020 19:01:10.961] [Worker-Main-6/INFO] [corgiaoc.byg.BYG/]: Reading json
[18Dec2020 19:01:10.961] [Worker-Main-6/ERROR] [corgiaoc.byg.BYG/]: byg:allium_fields's "climate" value is incorrect you put: "TEMPERATE". Defaulting climate to warm...
[18Dec2020 19:01:10.965] [Worker-Main-6/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2889/1892470159@432199ac
java.lang.NullPointerException
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130)
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:16)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:825)
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGBiomesJSONConfig(BYGJsonConfigHandler.java:36)
	at corgiaoc.byg.BYG.commonSetup(BYG.java:77)
	at corgiaoc.byg.BYG$$Lambda$3097/1465742522.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2889/1892470159.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at net.minecraftforge.fml.ModContainer$$Lambda$3057/215690645.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[18Dec2020 19:01:11.027] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[18Dec2020 19:01:10.967] [Worker-Main-6/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid byg
java.lang.NullPointerException: null
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:130) ~[?:1.1.5]
	at corgiaoc.byg.config.json.biomedata.BiomeDataListHolderSerializer.deserialize(BiomeDataListHolderSerializer.java:16) ~[?:1.1.5]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?]
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGBiomesJSONConfig(BYGJsonConfigHandler.java:36) ~[?:1.1.5]
	at corgiaoc.byg.BYG.commonSetup(BYG.java:77) ~[?:1.1.5]
	at corgiaoc.byg.BYG$$Lambda$3097/1465742522.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2889/1892470159.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:35.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3057/215690645.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[18Dec2020 19:01:11.655] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: AHEAD Current: 35.1.13 Target: null
[18Dec2020 19:01:15.054] [modloading-worker-1/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event COMMON_SETUP, 1 errors found
[18Dec2020 19:01:18.950] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.234] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.243] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.306] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.333] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.341] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.352] [Worker-Main-10/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[18Dec2020 19:01:20.432] [modloading-worker-1/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to process mod state change request from ENQUEUE_IMC
[18Dec2020 19:01:20.433] [modloading-worker-1/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to process mod state change request from PROCESS_IMC
[18Dec2020 19:01:20.434] [modloading-worker-1/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to process mod state change request from COMPLETE
[18Dec2020 19:01:24.923] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[18Dec2020 19:01:24.925] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[18Dec2020 19:01:25.686] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18Dec2020 19:01:25.875] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.876] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18Dec2020 19:01:25.877] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.877] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18Dec2020 19:01:25.879] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.879] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18Dec2020 19:01:25.882] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.891] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18Dec2020 19:01:25.892] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.892] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18Dec2020 19:01:25.893] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:25.893] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18Dec2020 19:01:25.894] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:27.611] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[18Dec2020 19:01:28.206] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18Dec2020 19:01:28.208] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:28.209] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18Dec2020 19:01:28.210] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:28.211] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18Dec2020 19:01:28.211] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18Dec2020 19:01:28.313] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID e8029993-71c9-4517-8429-a067aad1971b
[18Dec2020 19:01:28.314] [Render thread/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (23/26)
[18Dec2020 19:01:28.333] [Render thread/FATAL] [net.minecraftforge.fml.client.ClientModLoader/]: Crash report saved to C:\Users\dinny\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-18_19.01.28-fml.txt

**Comment by CorgiTaco** [comment]
Delete your config and let it reset.
