### ISSUE TITLE
Error message when I launch the game please help me

### ISSUE THREAD

**Issue by TybaltVg** [CorgiTaco/BYG#324]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
**2. Please test BYG on its own to confirm whether or not this is a mod conflict**

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__

__**API/Modloader**__
Forge 1.16.5

__**Describe the bug**__
Error message when I launch the game
It says: Oh  The Biome You'll Go (byg) encountered an error during the common_setup event phase java.lang.NullPointerException: null

![Capture d’écran 2021-03-02 à 10 19 35](https://user-images.githubusercontent.com/79904372/109626456-dcf37c00-7b40-11eb-8e05-926705813c3b.png)
__**To Reproduce**__
Please provide step by step instructions

**Expected behavior**

**Screenshots/Videos**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Logs**
Use: https://paste.ee/ and paste the links. if log is huge please upload those
Please provide:
Crashlog - 
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/03/21 10:07
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.0.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.0.43.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:85) ~[?:1.1.10] {re:classloading}
-- MOD byg --
Details:
	Mod File: byg-1.1.10.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.1.10
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:85) ~[?:1.1.10] {re:classloading}
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:13) ~[?:1.1.10] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGSubBiomesJSONConfig(BYGJsonConfigHandler.java:222) ~[?:1.1.10] {re:classloading}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleOverWorldConfig(BYGJsonConfigHandler.java:65) ~[?:1.1.10] {re:classloading}
	at corgiaoc.byg.BYG.commonSetup(BYG.java:81) ~[?:1.1.10] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.11.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1377319712 bytes (1313 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.43.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.43
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.43-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		byg-1.1.10.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.10              |ERROR     |NOSIGNATURE
		forge-1.16.5-36.0.43-universal.jar                |Forge                         |forge                         |36.0.43             |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: e8d78553-1fed-4c5a-a9bf-4119950a43c4

Debug.log - 
Latest.log - 

**Heap Dumps**
*If performance, please provide a heap dump/some sort of profile of your game(I recommend: https://visualvm.github.io/download.html)*
Heap Dump/Profile -

**Comment by CorgiTaco** [comment]
reset your config

**Comment by TybaltVg** [comment]
how?

**Comment by TybaltVg** [comment]
oooooooo tyyyyyyyyy
