### ISSUE TITLE
BYG: java.lang.NullPointerException

### ISSUE THREAD

**Issue by thatbeanboi** [CorgiTaco/BYG#362]
Exception message: java.lang.NullPointerException
Stacktrace:
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:85) ~[?:1.1.14] {re:classloading}
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:13) ~[?:1.1.14] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGSubBiomesJSONConfig(BYGJsonConfigHandler.java:222) ~[?:1.1.14] {re:classloading}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleOverWorldConfig(BYGJsonConfigHandler.java:65) ~[?:1.1.14] {re:classloading}
	at corgiaoc.byg.BYG.commonSetup(BYG.java:80) ~[?:1.1.14] {re:classloading}
	at corgiaoc.byg.BYG$$Lambda$9281/35191345.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2964/1438977874.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2575/739547794.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3826/810146988.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_45] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_45] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_45] {}

**Comment by ObjektivC** [comment]
Try resetting your configs

**Comment by CorgiTaco** [comment]
What Cslash said
