### ISSUE TITLE
Mangrove leaves lag the server so bad its almost unplayable

### ISSUE THREAD

**Issue by BudVanDoodle** [CorgiTaco/BYG#421]
The leaves also crashed the server at one point with this in the crash report.

java.lang.StackOverflowError: Exception ticking world
	at net.mcreator.byg.MCreatorMangroveleavesUpdateTick.executeProcedure(MCreatorMangroveleavesUpdateTick.java:17)
	at net.mcreator.byg.MCreatorMangroveleaves$BlockCustom.func_180650_b(MCreatorMangroveleaves.java:120)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.mcreator.byg.MCreatorMangroveleaves$BlockCustom.func_180650_b(MCreatorMangroveleaves.java:122)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.mcreator.byg.MCreatorMangroveleaves$BlockCustom.func_180650_b(MCreatorMangroveleaves.java:122)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)

is there a way to fix this or possibly just completely remove mangrove leaves from the game?

**Comment by CorgiTaco** [comment]
1.12 is no longer supported. Please use our latest version(1.16) for the best experience and to receive support!
