### ISSUE TITLE
Im having this crush why?

### ISSUE THREAD

**Issue by Giagua** [CorgiTaco/BYG#461]
Here is the crash report help pls

---- Minecraft Crash Report ----
// Why did you do that?

Time: 08/05/21 12.55
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7238/20794360.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6660/1520396451.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.debug.isometric.MixinGameRenderer_I,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1127434428.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:85) ~[?:1.2.7] {re:classloading}
-- MOD byg --
Details:
	Mod File: byg-1.2.7.jar
	Failure message: Oh The Biomes You'll Go (byg) encountered an error during the common_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.2.7
	Mod Issue URL: https://github.com/CorgiTaco/BYG/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:85) ~[?:1.2.7] {re:classloading}
	at corgiaoc.byg.config.json.subbiomedata.SubBiomeDataListHolderSerializer.deserialize(SubBiomeDataListHolderSerializer.java:13) ~[?:1.2.7] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?] {}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleBYGSubBiomesJSONConfig(BYGJsonConfigHandler.java:222) ~[?:1.2.7] {re:classloading}
	at corgiaoc.byg.config.json.BYGJsonConfigHandler.handleOverWorldConfig(BYGJsonConfigHandler.java:65) ~[?:1.2.7] {re:classloading}
	at corgiaoc.byg.BYG.commonSetup(BYG.java:85) ~[?:1.2.7] {re:classloading}
	at corgiaoc.byg.BYG$$Lambda$3885/369242742.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2994/2636011.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2593/172057768.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3227/187070277.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5681052144 bytes (5417 MB) / 7012876288 bytes (6688 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.16
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.12.0
	Mod List: 
		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		repurposed_structures-1.16.5-2.6.6-forge (1).jar  |Repurposed Structures         |repurposed_structures         |1.16.5-2.6.6-forge  |SIDED_SETU|NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |SIDED_SETU|NOSIGNATURE
		AmbientSounds_v3.1.6_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |SIDED_SETU|NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |SIDED_SETU|NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.465-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.463   |SIDED_SETU|NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.0.1.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.0.1        |SIDED_SETU|NOSIGNATURE
		Blur-1.1.0-1.jar                                  |Blur                          |blur                          |1.1.0-1             |SIDED_SETU|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |SIDED_SETU|NOSIGNATURE
		SaveYourPets-1.16.2-1.0.0.5.jar                   |Save Your Pets                |syp                           |1.0.0.5             |SIDED_SETU|NOSIGNATURE
		dungeons_plus-1.16.5-1.1.4.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.4               |SIDED_SETU|NOSIGNATURE
		CreativeCore_v2.1.3_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |SIDED_SETU|NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |SIDED_SETU|NOSIGNATURE
		personality-1.16.5-1.0.2.jar                      |Personality                   |personality                   |1.0.2               |SIDED_SETU|NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |SIDED_SETU|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |SIDED_SETU|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |SIDED_SETU|NOSIGNATURE
		villagernames_1.16.5-2.9.jar                      |Villager Names                |villagernames                 |2.9                 |SIDED_SETU|NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |SIDED_SETU|NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |SIDED_SETU|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |SIDED_SETU|NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.1.jar                |Traveler's Backpack           |travelersbackpack             |5.4.1               |SIDED_SETU|NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |SIDED_SETU|NOSIGNATURE
		EndReborn+[0.8.4].jar                             |End: Reborn                   |endreborn                     |0.8.4               |SIDED_SETU|NOSIGNATURE
		obfuscate-0.6.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.1               |SIDED_SETU|e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |SIDED_SETU|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |SIDED_SETU|NOSIGNATURE
		starterkit_1.16.5-2.4.jar                         |Starter Kit                   |starterkit                    |2.4                 |SIDED_SETU|NOSIGNATURE
		ForgivingVoid_1.16.3-5.2.0.jar                    |Forgiving Void                |forgivingvoid                 |5.2.0               |SIDED_SETU|NOSIGNATURE
		cobbler-1.6.1.jar                                 |Shulkers Faithful Factories   |cobbler                       |1.6.1               |SIDED_SETU|NOSIGNATURE
		byg-1.2.7.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.7               |ERROR     |NOSIGNATURE
		immersive-portals-0.16-mc1.16.5-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |SIDED_SETU|NOSIGNATURE
		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |SIDED_SETU|NOSIGNATURE
		Quark-r2.4-311.jar                                |Quark                         |quark                         |r2.4-311            |SIDED_SETU|NOSIGNATURE
		Aquaculture-1.16.5-2.1.18.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.18       |SIDED_SETU|NOSIGNATURE
		[1.16.X-1.0.10]+Dragon+Mounts+Legacy.jar          |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |SIDED_SETU|NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |SIDED_SETU|NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2 (1).jar        |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |SIDED_SETU|b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: 16ea3015-5b5f-4db7-85fc-b922c9ca30b4
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 Extreme-VL.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1660/PCIe/SSE2

**Comment by CorgiTaco** [comment]
Delete your configs

**Comment by Giagua** [comment]
How i delete my configs?
