### ISSUE TITLE
sudden compatibility bug with Antique Atlas and BYG

### ISSUE THREAD

**Issue by KirbyBrasse** [CorgiTaco/BYG#517]
**Before filling out this issue: **
**1. For major bugs, we only support BYG's latest version on a per Minecraft version basis(i.e latest for 1.15 is 1.0 while latest for 1.16 is 1.1).**
I play on the latest version of minecraft and your mod

__**Mod conflict? If so, please clarify which mod is conflicting, if not skip this.**__
Antique Atlas

__**API/Modloader**__
Forge latest version

__**Describe the bug**__
I can't open my save, the game crash when 100% loading is done

__**To Reproduce**__
i play on a modpack including AntiqueAtlas and BYG, i played without problem travelling far distance toward and Orchard, but when i closed the game and tried to reopen it afterward, it just wouldnt work

**Logs**
 i provide you with my latest log
https://drive.google.com/file/d/1v0AfeIAfUXlDXI7ewfb2N5eQlum4MW0X/view?usp=sharing

**Comment by CorgiTaco** [comment]
This should be reported to antique atlas because the NPE stems from their code: 
```
Caused by: java.lang.NullPointerException
	at hunternif.mc.impl.atlas.marker.GlobalMarkersDataHandler.onPlayerLogin(GlobalMarkersDataHandler.java:59) ~[?:?]
	at hunternif.mc.impl.atlas.forge.ForgeEvent.playerJoin(ForgeEvent.java:51) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_203_ForgeEvent_playerJoin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]

```
