### ISSUE TITLE
MixinConnector ClassNotFoundException

### ISSUE THREAD

**Issue by ghost** [CorgiTaco/BYG#520]
__**Mod conflict? If so, please clarify which mod is conflicting!**__
It is, but I'm having trouble knowing which mod is conflicting.

__**API/Modloader**__
Forge

__**Describe the bug**__
What is the bug? Where/How does it occur? etc.
It's just something I noticed in the console - maybe it's a non-issue, but it seems like a mixin shouldn't have a ClassNotFoundException.

__**To Reproduce**__
Download [my mods list](https://gist.github.com/Brittank88/d7b0e726322a364c8452f2b2fddfe78d) and start the game, I guess.

**Expected behavior**
No mixin failures, in an ideal world.

**Screenshots/Videos**
Literally neither but acts as a quick view of the issue:
```
[14Jun2021 22:50:54.009] [main/ERROR] [mixin/CATCHING]: Catching
java.lang.ClassNotFoundException: corgiaoc.byg.mixin.MixinConnector
	at java.lang.ClassLoader.findClass(ClassLoader.java:524) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_242]
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
		at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
		at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:57) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:71) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:60) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
		at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97) ~[modlauncher-8.0.9.jar:?]
		at java.util.HashMap.forEach(HashMap.java:1289) [?:1.8.0_242]
		at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Additional context**
I am still able to open the game and play in a world. I'm not sure what side effects this might be having though.

**Logs**
Please provide:
Crashlog - N/A
[Debug.log](https://gist.github.com/Brittank88/a57f48c5e1a0c77caaf4ba2d7c4c2ee1)
[Latest.log](https://gist.github.com/Brittank88/474e8f312cb53942f5bad5fde78b49a4)

**Comment by lynnpye** [comment]
What happens if you disable Upstream? After doing so, the exception no longer appears in my logs.

**Comment by ghost** [comment]
Unfortunately, it's been a little while since I've had time to touch Minecraft modpacks (😢).

Still, it would be awesome if you could create an issue with the Upstream devs, provided this is truly the incompatibility that is causing these errors!

**Comment by CorgiTaco** [comment]
This is in upstream
