### ISSUE TITLE
Crash when opening game MC 1.16.5

### ISSUE THREAD

**Issue by Gamesgamesilove** [CorgiTaco/BYG#573]
### Mod Version

BYG 1.3.4

### Mod Loader

Fabric

### Mod Loader Version

0.11.7

### What happened?

I opened minecraft, and this appeared The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'byg'!
Exit Code: -1 

### latest.log

---- Minecraft Crash Report ----
// There are four lights!

Time: 9/30/21 1:51 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'byg'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.IllegalArgumentException: No enum constant corgiaoc.byg.util.MLClimate.TEMPERATE
	at java.lang.Enum.valueOf(Enum.java:238)
	at corgiaoc.byg.util.MLClimate.valueOf(MLClimate.java:11)
	at corgiaoc.byg.util.MLClimate.byName(MLClimate.java:31)
	at corgiaoc.byg.util.MLClimate$$Lambda$5360/1974253327.apply(Unknown Source)
	at net.minecraft.class_3542$1.method_28148(class_3542.java:44)
	at net.minecraft.class_3542$1$$Lambda$5384/1959403133.apply(Unknown Source)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.serialization.DataResult$$Lambda$745/401299544.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at net.minecraft.class_3542$1.decode(class_3542.java:44)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29)
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:323)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:405)
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
	at com.mojang.serialization.MapDecoder$$Lambda$5373/2136753211.apply(Unknown Source)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.serialization.DataResult$$Lambda$745/401299544.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at com.mojang.serialization.codecs.BaseMapCodec.lambda$decode$2(BaseMapCodec.java:31)
	at com.mojang.serialization.codecs.BaseMapCodec$$Lambda$5376/215865331.apply(Unknown Source)
	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:484)
	at com.mojang.serialization.codecs.BaseMapCodec.decode(BaseMapCodec.java:27)
	at com.mojang.serialization.codecs.UnboundedMapCodec.lambda$decode$0(UnboundedMapCodec.java:38)
	at com.mojang.serialization.codecs.UnboundedMapCodec$$Lambda$5374/810374430.apply(Unknown Source)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.serialization.DataResult$$Lambda$745/401299544.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.codecs.UnboundedMapCodec.decode(UnboundedMapCodec.java:38)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29)
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$1.decode(RecordCodecBuilder.java:183)
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
	at com.mojang.serialization.MapDecoder$$Lambda$5373/2136753211.apply(Unknown Source)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.serialization.DataResult$$Lambda$745/401299544.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at corgiaoc.byg.BYG.handleOverWorldConfig(BYG.java:196)
	at corgiaoc.byg.BYG.threadSafeCommonLoad(BYG.java:100)
	at corgiaoc.byg.entrypoint.FabricEntryPoint.commonSetup(FabricEntryPoint.java:53)
	at corgiaoc.byg.entrypoint.FabricEntryPoint.onInitialize(FabricEntryPoint.java:46)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2267/1232147275.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 893736688 bytes (852 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		added_origins_mod: Added Origins V2.0.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automatone: Automatone 0.3.6
		bclib: BCLib 0.1.45
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.8.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		bewitchment: Bewitchment 1.16.5-18
		byg: BYG 1.3.4
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.2
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		chat_heads: Chat Heads 0.2.2+1.16.2
		chime: Chime 1.1.3
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		collectionorigins1: Imperium Origins Collection 1 2.0
		collectionorigins2: Imperium Origins Collection 2 2.0
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.7
		croptopia: Croptopia 1.4.0
		croptosis: Croptosis 1.1.0
		darkrites: Dark Rites 1.16.5-2
		decorative: Decorative 4.0.0
		enchant_giver: Enchant Giver 1.0.3
		enchdesc: EnchantmentDescriptions 2.0.8
		enva: Environmental Armor 1.3.1
		expandedstorage: Expanded Storage 7.0.2
		extraalchemy: Extra Alchemy 1.4.5
		extraorigins: Extra Origins 1.16.5-12
		fabric: Fabric API 0.40.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+f74f7c7d7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+f74f7c7d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+f74f7c7d7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+f74f7c7d7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+f74f7c7d7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+f74f7c7d7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+77df1b337d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.4+35ff49a47d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+f74f7c7d7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+f74f7c7d7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+f74f7c7d7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.4+f74f7c7d7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+f74f7c7d7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f74f7c7d7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+f74f7c7d7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4579bd497d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+f74f7c7d7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+f74f7c7d7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+f74f7c7d7d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4579bd497d
		fabricloader: Fabric Loader 0.11.7
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.3.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		genesis: Genesis 0.5.1
		illuminations: Illuminations 1.5.1
		impersonate: Impersonate 2.2.1
		inmis: Inmis 2.2.1-1.16.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		latoorigins: Lato Origins 0.7.3
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		locki: Locki 0.2.1
		magna: Magna 1.5.3-1.16.5
		mayaorigin: A Maya Origin 2.0
		maybe-data: Maybe data 1.0.0-1.16.2
		mcda: MC Dungeons Armors 1.5.0
		mcdar: MC Dungeons Artifacts 1.2.0
		mcdw: MC Dungeons Weapons 3.2.0
		mcsa: MC Story Mode Armor 2.3.2
		mementomori: Memento Mori 2.3.1+1.16.5-fabric
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		moborigins: Mob Origins 1.4.0
		modern_industrialization: Modern Industrialization 0.4.0-alpha.11
		modmenu: Mod Menu 1.16.21
		mysticalagriculture: Mystical Agriculture: Refabricated 1.1.7
		mythorigins: Myth Origins 0.1.0
		omega-config: OmegaConfig 1.0.4
		onsoulfire: On Soul Fire 1.16.5-2
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		originsumbrellas: Origins: Umbrellas 1.1.0
		pandemonium: Requiem: Pandemonium 1.7.14
		pandemoniumapi: Requiem: Pandemonium-API 1.7.14
		patchouli: Patchouli 1.16.4-53-FABRIC
		pehkui: Pehkui 2.4.0+1.14.4-1.17.1
		playerabilitylib: Pal 1.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reauth: ReAuth 3.9.3
		reborncore: Reborn Core 4.7.3+build.136
		requiem: Requiem 1.7.14
		requiemapi: Requiem-API 1.7.14
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		roughlyenoughresources: Roughly Enough Resources 2.1.5
		satin: Satin 1.5.1
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		somnus: Somnus API 0.0.12-1.16.5
		spark: spark 1.6.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.4+build.236
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		trinkets: Trinkets 2.6.7
		vanilla-hammers: Vanilla Hammers 3.0.3-1.16.5
		wiicustomorigins: Fox Origins Mod 1.0.0
		wildfire_gender: Wildfire's Female Gender Mod 2.8
		witheran: Witheran Origin 1.0.3
		worldedit: WorldEdit 7.2.2+fc3c499
		xaerominimapfair: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.17.0
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.7-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by CorgiTaco** [comment]
Reset your configs

**Comment by Gamesgamesilove** [comment]
> Reset your configs

how? im sorry im new

**Comment by enduum** [comment]
@Gamesgamesilove Go to your .minecraft\config folder. Inside is a folder just named byg. Delete the byg folder, and then launch the game. :)
