### ISSUE TITLE
Crash on fabric with biome makeover, terrablender and continuity

### ISSUE THREAD

**Issue by nullified33** [CorgiTaco/BYG#620]
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_437.method_25412(class_437.java:496)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_312.method_1601(class_312.java:94)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_312.method_22686(class_312.java:165)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_1255.execute(class_1255.java:101)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_312.method_22684(class_312.java:165)
[17/01/2022 19:13:06 PM] 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[17/01/2022 19:13:06 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17/01/2022 19:13:06 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17/01/2022 19:13:06 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1142)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_310.method_1514(class_310.java:733)
[17/01/2022 19:13:06 PM] 	at net.minecraft.client.main.Main.main(Main.java:238)
[17/01/2022 19:13:06 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/01/2022 19:13:06 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17/01/2022 19:13:06 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17/01/2022 19:13:06 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17/01/2022 19:13:06 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[17/01/2022 19:13:06 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[17/01/2022 19:13:06 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17/01/2022 19:13:06 PM] Caused by: java.lang.ClassCastException: class net.minecraft.class_5818 cannot be cast to class terrablender.worldgen.TBClimate$Sampler (net.minecraft.class_5818 and terrablender.worldgen.TBClimate$Sampler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @63dd899)
[17/01/2022 19:13:06 PM] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.method_38109(TBMultiNoiseBiomeSource.java:94)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_1966.method_24385(class_1966.java:227)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_1966.method_8762(class_1966.java:191)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_2794.method_28509(class_2794.java:133)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_2794.invokeGenerateStrongholdPositions(class_2794.java)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_3754.handler$bij006$onInit(class_3754.java:4088)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:124)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:84)
[17/01/2022 19:13:06 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:68)
[17/01/2022 19:13:06 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:63)
[17/01/2022 19:13:06 PM] 	at terrablender.api.WorldPresetUtils.chunkGenerator(WorldPresetUtils.java:110)
[17/01/2022 19:13:06 PM] 	at terrablender.api.WorldPresetUtils.overworldChunkGenerator(WorldPresetUtils.java:48)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_5317$1.handler$gea000$modifyGenerator(class_5317.java:551)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_5317$1.method_29076(class_5317.java)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_5317$1.method_29077(class_5317.java:558)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_525.redirect$ged000$onMakeDefault(class_525.java:1169)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_525.method_31130(class_525.java:142)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_528.method_2750(class_528.java:103)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_528.<init>(class_528.java:85)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_526.method_25426(class_526.java:65)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_437.method_25423(class_437.java:388)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_310.method_1507(class_310.java:989)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_442.method_19861(class_442.java:145)
[17/01/2022 19:13:06 PM] 	at net.minecraft.class_4185.method_25306(class_4185.java:40)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_4264.method_25348(class_4264.java:16)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_339.method_25402(class_339.java:121)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_4069.method_25402(class_4069.java:27)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_442.method_25402(class_442.java:312)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_312.method_1611(class_312.java:94)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_437.method_25412(class_437.java:491)
[17/01/2022 19:13:07 PM] 	... 19 more
[17/01/2022 19:13:07 PM] [Render thread/FATAL] Reported exception thrown!
[17/01/2022 19:13:07 PM] ---- Minecraft Crash Report ----
[17/01/2022 19:13:07 PM] // You should try our sister game, Minceraft!
[17/01/2022 19:13:07 PM] 
[17/01/2022 19:13:07 PM] Time: 1/17/22, 7:13 PM
[17/01/2022 19:13:07 PM] Description: mouseClicked event handler
[17/01/2022 19:13:07 PM] 
[17/01/2022 19:13:07 PM] java.lang.ClassCastException: class net.minecraft.class_5818 cannot be cast to class terrablender.worldgen.TBClimate$Sampler (net.minecraft.class_5818 and terrablender.worldgen.TBClimate$Sampler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @63dd899)
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.method_38109(TBMultiNoiseBiomeSource.java:94)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1966.method_24385(class_1966.java:227)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1966.method_8762(class_1966.java:191)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_2794.method_28509(class_2794.java:133)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_2794.invokeGenerateStrongholdPositions(class_2794.java)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.handler$bij006$onInit(class_3754.java:4088)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:124)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:84)
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:68)
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:63)
[17/01/2022 19:13:07 PM] 	at terrablender.api.WorldPresetUtils.chunkGenerator(WorldPresetUtils.java:110)
[17/01/2022 19:13:07 PM] 	at terrablender.api.WorldPresetUtils.overworldChunkGenerator(WorldPresetUtils.java:48)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_5317$1.handler$gea000$modifyGenerator(class_5317.java:551)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_5317$1.method_29076(class_5317.java)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_5317$1.method_29077(class_5317.java:558)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_525.redirect$ged000$onMakeDefault(class_525.java:1169)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_525.method_31130(class_525.java:142)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_528.method_2750(class_528.java:103)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_528.<init>(class_528.java:85)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_526.method_25426(class_526.java:65)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_437.method_25423(class_437.java:388)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_310.method_1507(class_310.java:989)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_442.method_19861(class_442.java:145)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_4185.method_25306(class_4185.java:40)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_4264.method_25348(class_4264.java:16)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_339.method_25402(class_339.java:121)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_4069.method_25402(class_4069.java:27)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_442.method_25402(class_442.java:312)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_312.method_1611(class_312.java:94)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_437.method_25412(class_437.java:491)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_312.method_1601(class_312.java:94)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_312.method_22686(class_312.java:165)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1255.execute(class_1255.java:101)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_312.method_22684(class_312.java:165)
[17/01/2022 19:13:07 PM] 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[17/01/2022 19:13:07 PM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17/01/2022 19:13:07 PM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17/01/2022 19:13:07 PM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1142)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_310.method_1514(class_310.java:733)
[17/01/2022 19:13:07 PM] 	at net.minecraft.client.main.Main.main(Main.java:238)
[17/01/2022 19:13:07 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/01/2022 19:13:07 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17/01/2022 19:13:07 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17/01/2022 19:13:07 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17/01/2022 19:13:07 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[17/01/2022 19:13:07 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[17/01/2022 19:13:07 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17/01/2022 19:13:07 PM] 
[17/01/2022 19:13:07 PM] 
[17/01/2022 19:13:07 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[17/01/2022 19:13:07 PM] ---------------------------------------------------------------------------------------
[17/01/2022 19:13:07 PM] 
[17/01/2022 19:13:07 PM] -- Head --
[17/01/2022 19:13:07 PM] Thread: Render thread
[17/01/2022 19:13:07 PM] Stacktrace:
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.method_38109(TBMultiNoiseBiomeSource.java:94)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1966.method_24385(class_1966.java:227)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_1966.method_8762(class_1966.java:191)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_2794.method_28509(class_2794.java:133)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_2794.invokeGenerateStrongholdPositions(class_2794.java)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.handler$bij006$onInit(class_3754.java:4088)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:124)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_3754.<init>(class_3754.java:84)
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:68)
[17/01/2022 19:13:07 PM] 	at terrablender.worldgen.TBNoiseBasedChunkGenerator.<init>(TBNoiseBasedChunkGenerator.java:63)
[17/01/2022 19:13:07 PM] 	at terrablender.api.WorldPresetUtils.chunkGenerator(WorldPresetUtils.java:110)
[17/01/2022 19:13:07 PM] 	at terrablender.api.WorldPresetUtils.overworldChunkGenerator(WorldPresetUtils.java:48)
[17/01/2022 19:13:07 PM] 	at net.minecraft.class_5317$1.handler$gea000$modifyGenerator(class_5317.java:551)
[17/01/2022 19:13:08 PM] 		biomemakeover: Biome Makeover 1.18.1-ALPHA5
[17/01/2022 19:13:08 PM] 		continuity: Continuity 1.0.3+1.18
[17/01/2022 19:13:08 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\SemiModdedLife\crash-reports\crash-2022-01-17_19.13.06-client.txt
[17/01/2022 19:13:08 PM] AL lib: (EE) alc_cleanup: 1 device not closed
[17/01/2022 19:13:08 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[17/01/2022 19:13:12 PM] Checking for updated files!
[17/01/2022 19:13:12 PM] Checking for updates to CurseForge instances

**Comment by nullified33** [comment]
C2ME
