### ISSUE TITLE
[Bug]: undergarden compatibility

### ISSUE THREAD

**Issue by arzadu** [CorgiTaco/BYG#648]
### Mod Version

1.3.5.12

### Mod Loader

Forge

### Mod Loader Version

39.0.85

### What happened?

BYG crashes with Undergarden installed - I added them both to a modpack and BYG worked fine with plenty of other mods, but Undergarden broke it (maybe something with additional dimension generation? that's my uneducated guess, anyway). Crash log pasted below. 

[crash-2022-02-24_20.06.49-client.txt](https://github.com/AOCAWOL/BYG/files/8137631/crash-2022-02-24_20.06.49-client.txt)

### latest.log

Sorry for not including the file, it included my name (which I'm not comfortable sharing).

`
[20:05:15] [main/INFO]: ModLauncher running: args [--username, arzadu, --version, forge-39.0.85, --gameDir, /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden, --assetsDir, /Users/(REDACTED)/Documents/curseforge/minecraft/Install/assets, --assetIndex, 1.18, --uuid, 8152a76fd26a412f816800cdb32140cd, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, RUYzQUM2ODM3QzM5NEZDMUI4NzkxNzNGRTMzMDQ0QzM=, --xuid, 2535424729509403, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.85, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[20:05:15] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Microsoft
[20:05:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/(REDACTED)/Documents/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=CLIENT
[20:05:15] [main/WARN]: Configuration file /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/fml.toml is not correct. Correcting
[20:05:15] [main/WARN]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[20:05:15] [main/INFO]: Found mod file Oh The Biomes You'll Go-forge-1.18.1-1.3.5.12.jar of type MOD with locator {mods folder locator at /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/mods}
[20:05:15] [main/INFO]: Found mod file TerraBlender-forge-1.18.1-1.1.0.73.jar of type MOD with locator {mods folder locator at /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/mods}
[20:05:15] [main/INFO]: Found mod file The_Undergarden-1.18.1-0.6.3.jar of type MOD with locator {mods folder locator at /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/mods}
[20:05:16] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.85.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2d0566ba
[20:05:16] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.85.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2d0566ba
[20:05:16] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.85.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2d0566ba
[20:05:16] [main/INFO]: Found mod file client-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2d0566ba
[20:05:16] [main/INFO]: Found mod file forge-1.18.1-39.0.85-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2d0566ba
[20:05:19] [main/INFO]: Compatibility level set to JAVA_17
[20:05:19] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-39.0.85, --gameDir, /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden, --assetsDir, /Users/(REDACTED)/Documents/curseforge/minecraft/Install/assets, --uuid, 8152a76fd26a412f816800cdb32140cd, --username, arzadu, --assetIndex, 1.18, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, RUYzQUM2ODM3QzM5NEZDMUI4NzkxNzNGRTMzMDQ0QzM=, --xuid, 2535424729509403, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[20:05:19] [main/WARN]: Reference map 'undergarden.refmap.json' for undergarden.mixins.json could not be read. If this is a development environment you can ignore this message
[20:05:37] [Render thread/WARN]: Assets URL 'union:/Users/(REDACTED)/Documents/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2356!/assets/.mcassetsroot' uses unexpected schema
[20:05:37] [Render thread/WARN]: Assets URL 'union:/Users/(REDACTED)/Documents/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2356!/data/.mcassetsroot' uses unexpected schema
[20:05:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:05:39] [Render thread/INFO]: Setting user: arzadu
[20:05:39] [Render thread/INFO]: Backend library: LWJGL version 3.2.1 SNAPSHOT
[20:05:40] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.85, for MC 1.18.1 with MCP 20211210.034407
[20:05:40] [modloading-worker-0/INFO]: MinecraftForge v39.0.85 Initialized
[20:05:44] [Render thread/ERROR]: Error while loading the narrator : java.lang.NoClassDefFoundError: com/sun/jna/PointerTool
[20:05:45] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[20:05:45] [modloading-worker-0/WARN]: Configuration file /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/forge-client.toml is not correct. Correcting
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client was corrected from null to its default, SimpleCommentedConfig:{}. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client.alwaysSetupTerrainOffThread was corrected from null to its default, false. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from null to its default, false. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client.showLoadWarnings was corrected from null to its default, true. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client.useCombinedDepthStencilAttachment was corrected from null to its default, false. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key client.forceSystemNanoTime was corrected from null to its default, false. 
[20:05:45] [modloading-worker-0/WARN]: Configuration file /Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/forge-common.toml is not correct. Correcting
[20:05:45] [modloading-worker-0/WARN]: Incorrect key general was corrected from null to its default, SimpleCommentedConfig:{}. 
[20:05:45] [modloading-worker-0/WARN]: Incorrect key general.defaultWorldType was corrected from null to its default, default. 
[20:05:45] [Worker-Main-5/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-sapling-patterns.json" was read.
[20:05:45] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[20:05:45] [Worker-Main-5/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-end-biomes.json" was read.
[20:05:45] [Worker-Main-5/INFO]: BYG: "Common Setup" Event Complete!
[20:05:45] [Worker-Main-5/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-biome-dictionary.json" was read.
[20:05:46] [Forge Version Check/INFO]: [forge] Found status: BETA Current: 39.0.85 Target: 39.0.85
[20:06:06] [Worker-Main-5/WARN]: Exception loading blockstate definition: byg:blockstates/potted_hydrangea_bush.json: java.io.FileNotFoundException: byg:blockstates/potted_hydrangea_bush.json
[20:06:06] [Worker-Main-5/WARN]: Exception loading blockstate definition: 'byg:blockstates/potted_hydrangea_bush.json' missing model for variant: 'byg:potted_hydrangea_bush#'
[20:06:22] [Render thread/INFO]: Registered biome provider minecraft:biome_provider to index 0
[20:06:22] [Render thread/INFO]: Registered biome provider byg:surface_data to index 1
[20:06:22] [Render thread/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/overworld-biomes.json" was read.
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_0 to index 2
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_1 to index 3
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_2 to index 4
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_3 to index 5
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_4 to index 6
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_5 to index 7
[20:06:22] [Render thread/INFO]: Registered biome provider byg:biome_provider_6 to index 8
[20:06:22] [Worker-Main-8/INFO]: BYG: "Client Setup" Event Complete!
[20:06:26] [Render thread/INFO]: BYG: Compostible Blocks Added!
[20:06:26] [Render thread/INFO]: BYG: Added tillables!
[20:06:26] [Render thread/INFO]: BYG: Added Flammables!
[20:06:26] [Render thread/INFO]: BYG: Added strippable Blocks...
[20:06:26] [Render thread/INFO]: BYG: "Load Complete" Event Complete!
[20:06:33] [Render thread/INFO]: OpenAL initialized on device CoreAudio Default
[20:06:33] [Render thread/INFO]: Sound engine started
[20:06:34] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:06:34] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:06:34] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:06:34] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:06:34] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:06:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:06:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:06:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:06:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:06:39] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:06:46] [Render thread/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-end-biomes.json" was read.
[20:06:46] [Render thread/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-end-biomes.json" was read.
[20:06:46] [Render thread/INFO]: "/Users/(REDACTED)/Documents/curseforge/minecraft/Instances/byg undergarden/config/byg/byg-end-biomes.json" was read.
[20:06:49] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:534) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.1.jar%2348!/:build 12]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.1.jar%2344!/:build 12]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050) ~[lwjgl-glfw-3.2.1.jar%2348!/:build 12]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:195) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1062) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.85.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IllegalAccessError: class potionstudios.byg.world.biome.LayerUtil tried to access private method 'terrablender.worldgen.noise.AreaFactory terrablender.worldgen.noise.LayeredNoiseUtil.zoom(long, terrablender.worldgen.noise.AreaTransformer1, terrablender.worldgen.noise.AreaFactory, int, java.util.function.LongFunction)' (potionstudios.byg.world.biome.LayerUtil is in module byg@1.3.5.12 of loader 'TRANSFORMER' @6caf7803; terrablender.worldgen.noise.LayeredNoiseUtil is in module terrablender@1.18.1-1.1.0.73 of loader 'TRANSFORMER' @6caf7803)
	at potionstudios.byg.world.biome.LayerUtil.createLayers(LayerUtil.java:25) ~[Oh%20The%20Biomes%20You'll%20Go-forge-1.18.1-1.3.5.12.jar%2353!/:1.3.5.12]
	at potionstudios.byg.world.biome.BYGForgeEndBiomeSource.getIslandBiomeResolver(BYGForgeEndBiomeSource.java:36) ~[Oh%20The%20Biomes%20You'll%20Go-forge-1.18.1-1.3.5.12.jar%2353!/:1.3.5.12]
	at potionstudios.byg.common.world.biome.BYGEndBiomeSource.<init>(BYGEndBiomeSource.java:66) ~[Oh%20The%20Biomes%20You'll%20Go-forge-1.18.1-1.3.5.12.jar%2353!/:1.3.5.12]
	at potionstudios.byg.world.biome.BYGForgeEndBiomeSource.<init>(BYGForgeEndBiomeSource.java:31) ~[Oh%20The%20Biomes%20You'll%20Go-forge-1.18.1-1.3.5.12.jar%2353!/:1.3.5.12]
	at net.minecraft.world.level.dimension.DimensionType.handler$zca000$useBYGEnd(DimensionType.java:542) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.world.level.dimension.DimensionType.m_188317_(DimensionType.java:217) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at terrablender.api.WorldPresetUtils.dimensions(WorldPresetUtils.java:121) ~[TerraBlender-forge-1.18.1-1.1.0.73.jar%2354!/:1.18.1-1.1.0.73]
	at net.minecraft.client.gui.screens.worldselection.WorldPreset$1.m_7012_(WorldPreset.java:558) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$create$0(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100898_(CreateWorldScreen.java:119) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.m_101676_(WorldSelectionList.java:103) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.<init>(WorldSelectionList.java:85) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_7856_(SelectWorldScreen.java:65) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:422) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:915) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_169449_(TitleScreen.java:147) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_6375_(TitleScreen.java:345) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2356!/:?]
	... 25 more
[20:06:49] [Render thread/FATAL]: Preparing crash report with UUID 674d61de-e7b1-4ad3-923f-912d73ec80a0
[20:06:49] [Render thread/FATAL]: Preparing crash report with UUID 37b56926-4871-4362-8946-8ca77c9b09c9
`

**Comment by CorgiTaco** [comment]
Update terrablender https://www.curseforge.com/minecraft/mc-mods/terrablender/files/3651452
