### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Samlegamer** [CorgiTaco/BYG#665]
### Mod Version

Oh The Biomes You'll Go-forge-1.18.2-1.4-ALPHA

### Mod Loader

Forge

### Mod Loader Version

Forge 1.18.2-0.42

### What happened?

The game crashes when you load a flat world

### latest.log

---- Minecraft Crash Report ----
// My bad.

Time: 10/03/2022 22:07
Description: Exception in server tick loop

java.lang.ClassCastException: class net.minecraft.world.level.levelgen.FlatLevelSource cannot be cast to class potionstudios.byg.mixin.access.NoiseBasedChunkGeneratorAccess (net.minecraft.world.level.levelgen.FlatLevelSource is in module minecraft@1.18.2 of loader 'TRANSFORMER' @46aa712c; potionstudios.byg.mixin.access.NoiseBasedChunkGeneratorAccess is in module byg@1.4-ALPHA of loader 'TRANSFORMER' @46aa712c)
	at net.minecraft.server.MinecraftServer.handler$zbg000$hackyAddNetherAndEndSurfaceRules(MinecraftServer.java:1977) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:403) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:316) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:64) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220228.144236-srg.jar%2356!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by CorgiTaco** [comment]
Fixed in https://github.com/AOCAWOL/BYG/commit/959998b1884a000f7ff29319e43c8226527867cc
