### ISSUE TITLE
[Crash]:  crashes on placing lectern

### ISSUE THREAD

**Issue by ribcage1103** [CorgiTaco/BYG#693]
### Minecraft Version

1.18.2

### BYG Versions

1,18.1-1.4-RC-7

### Terrablender

1.18.2-1.1.0.94

### Mod Loader

Fabric

### Mod Loader Version

fabric 0.13,3

### What happened?

Hello,
I'm using the Medieval Minecraft modpack fabric 1,18,2. I also added some mods to it, but it seems they are all compatible with each other, everything is working fine only when I place a lectern it crashes the game. I also can't craft a lectern with normal vanilla woods only  with modded ones, I even tried taking one from creative mode and still chrashes. I hope I posted the right chrash log and latest log

### crash-log

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/28/22, 6:11 PM
Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3722$1 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.block.entity.LecternBlockEntity.<init>(LecternBlockEntity:40)
	at net.minecraft.block.LecternBlock.createBlockEntity(LecternBlock:153)
	at net.minecraft.world.chunk.WorldChunk.createBlockEntity(WorldChunk:292)
	at net.minecraft.world.chunk.WorldChunk.getBlockEntity(WorldChunk:315)
	at net.minecraft.world.World.getBlockEntity(World:533)
	at mcp.mobius.waila.access.DataAccessor.set(DataAccessor.java:175)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:76)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:51)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:22)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$ccj000$onEndTick(MinecraftClient:11472)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1817)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$eak000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:19521)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:764)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$eak000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:19521)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:764)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 31 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/class_1657;)D in mixins.reach-entity-attributes.json:InventoryValidationMixin from mod reach-entity-attributes failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 34 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3722.<init>(class_3722.java:40)
	at net.minecraft.class_3715.method_10123(class_3715.java:153)
	at net.minecraft.class_2818.method_12208(class_2818.java:292)
	at net.minecraft.class_2818.method_12201(class_2818.java:315)
	at net.minecraft.class_1937.method_8321(class_1937.java:533)
	at mcp.mobius.waila.access.DataAccessor.set(DataAccessor.java:175)
	at mcp.mobius.waila.hud.ClientTickHandler.tick(ClientTickHandler.java:76)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:51)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:22)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$ccj000$onEndTick(class_310.java:11472)

-- Affected level --
Details:
	All players: 2 total; [class_746['StoppedToast898'/546787, l='ClientLevel', x=-204.46, y=47.00, z=1314.03], class_745['PeachySpace637'/546263, l='ClientLevel', x=-326.47, y=72.00, z=1239.38]]
	Chunk stats: 16384, 467
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,-128), Section: (at 0,2,0 in 0,4,-8; chunk contains blocks 0,-64,-128 to 15,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 123479 game time, 176550 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$eak000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:19521)
	at net.minecraft.class_310.method_1514(class_310.java:764)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$eak000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:19521)
	at net.minecraft.class_310.method_1514(class_310.java:764)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Excalibur_V1.18.zip, Fabric_Friendly_Excalibur_1.18.2_v1.0.zip, Excalibur_Mod_Support_V1.18.1.1.zip, Caliburn_Variations_v1.0_-_1.18.zip, Caliburn_Leaves_v2.1_-_1.18.zip, Wooden Door Sounds.zip, STONEBORN - 1.18 - V3.1.zip, STONEBORN - 1.18 - EXTENDED V1.3.zip, EmbellishedStone-1.18-1.0.0.zip, Mizunos 16 Craft JE CIT_1.18.1-1.0.zip, EclecticTrove-1.18-1.0.1.zip, Invisible Item Frame Pack_1.18.1-1.0.zip, Xaero's Minimap - Mod Icons.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 560688632 bytes (534 MiB) / 2097152000 bytes (2000 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24493.76
	Virtual memory used (MB): 12681.88
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 108.21
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalstructures: Additional Structures 3.0.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.10
		alloy_forgery: Alloy Forgery 2.0.10+1.18
		amecsapi: Amecs API 1.3.5+mc22w06a
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdcaracal: Caracal mob 1.18-1.3.7.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architectury: Architectury 4.1.34
		attributefix: AttributeFix 14.0.1
		autoconfig1u: Auto Config v1 Updated 3.4.0
		backslot: BackSlot 1.2.6
		backslotaddon: BackSlot Addon 1.0.8
		balm-fabric: Balm 3.0.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		betterf3: BetterF3 1.2.4
		betterthirdperson: Better Third Person 1.6.0
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		big_items_duh: Big items, duh! 1.1.1+mc1.18.2
		biomeinfo: BiomeInfo 1.18.2-10
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bookshelf: Bookshelf 13.0.7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.6-1.18.2
		byg: Oh The Biomes You'll Go 1.4-RC-7
		capybara: Capybara 1.0.3
		cardinal-components: Cardinal Components API 4.1.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.1.4
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.1.4
		cardinal-components-level: Cardinal Components API (world saves) 4.1.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		carrier: Carrier 1.10.0
		cem: Custom Entity Models 0.7.1
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		clickadv: Clickable Advancements Mod 2.5
		clienttweaks: Client Tweaks 7.1.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.0+7
		coat: Coat 1.0.0-beta.17+mc1.18.2
		collective-fabric: Collective (Fabric) 4.26
		colormatic: Colormatic 3.1.1+mc.1.18.2
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.1.2-1.18.2
		companion: Companion 2.0.0
		completeconfig: CompleteConfig 1.0.0
		conjuring: Conjuring 1.0.22+1.18
		continuity: Continuity 1.1.0+1.18.2
		controlling: Controlling For Fabric 9.0+17
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 1.3.0
		croparia: Croparia 3.8.3
		croptopia: Croptopia 1.8.3
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 10.0.1
		dashloader: DashLoader 3.0.1+1.18
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.2
		deleteworldstotrash: Delete Worlds To Trash 3.2.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.3.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disenchanter: Disenchanter 0.1.5+1.18
		doubledoors-fabric: Double Doors (Fabric) 3.3
		dragonloot: DragonLoot 1.0.10
		drippyloadingscreen: Drippy Loading Screen 1.5.1
		dynamicfps: Dynamic FPS 2.1.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easymagic: Easy Magic 3.3.0
		easyshulkerboxes: Easy Shulker Boxes 3.1.0
		eldritch_mobs: Eldritch Mobs 1.11.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchant_giver: Enchant Giver 1.1.0
		enchantinginfuser: Enchanting Infuser 3.2.0
		enchantment_lore: Enchantment Lore 1.2.6-1
		enchdesc: EnchantmentDescriptions 10.0.2
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		entity_texture_features: Entity Texture Features 2.5.6
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.11
		exlinefurniture: Exline's Furniture fabric-1.18.2-v2.0.5
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		fallingtree: FallingTree 3.4.1
		fancymenu: FancyMenu 2.6.4
		farsight: Farsight Mod 1.18-1.8
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.0
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.1.0
		flesh2leather: Flesh2Leather 1.0.3+1.18.2
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.2.6
		geckolib3: Geckolib 3.0.35
		geodes: More Geodes 1.3-SNAPSHOT.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.7
		graveyard_biomes: The Graveyard Biomes 1.1
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.10
		harvest_scythes: Harvest Scythes 2.5.0
		highlighter: Highlighter 1.1.2
		hookshot: Hookshot 25.0
		hoverpets: Hover Pets 0.3.1
		icarus: Icarus 1.10
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.2+mc1.18.2
		inmis: Inmis 2.5.2-1.18.2
		interactic: Interactic 0.1.10+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.6-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.2-build.32
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.5+1.14.4-1.18.2
		kirin: Kirin UI 1.10.0
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		kyrptconfig: Kyrpt Config 1.4.2-1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libgui: LibGui 5.3.1+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		lovely_snails: Lovely Snails 1.0.4+1.18
		maelstrom_library: Maelstrom Library 1.2.4-1.18.2
		magna: Magna 1.7.0-1.18-pre1
		magnumtorch: Magnum Torch 3.1.2
		mambience: MAmbience 5.0.0+1.18.2
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-more-data: Maybe More Data 1.0.0-1.18.2
		mcda: MC Dungeons Armors 2.0.4
		mcdw: MC Dungeons Weapons 4.2.5
		medievalmusic: Medieval Music Mod 1.18-1.3
		medievalweapons: Medieval Weapons 1.1.9
		megaparrot: Megaparrot 1.0.4
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.1.0
		moreachievements: MoreAchievements 1.0.8
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.22
		multipart_entities: MultipartEntities 1.1.5-1.18.2
		mythic-mounts: Mythic Mounts 1.18.2-5.0
		mythicmetals: Mythic Metals 0.13.0
		mythicmetals_decorations: Mythic Metals Decorations 0.1.2
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.2
		notenoughanimations: NotEnoughAnimations 1.5.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.3-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		owo: oωo 0.6.0+1.18
		oxidized: Oxidized 1.6.3
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		patchouli: Patchouli 1.18.2-66-FABRIC
		paxi: Paxi 1.18.2-Fabric-2.0
		pehkui: Pehkui 3.2.0+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
		pigsteel: Pigsteel Mod 1.7.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player-data-api: Player Data API 0.1.0+1.18
		polymorph: Polymorph 0.0.20-1.18.2
		presencefootsteps: Presence Footsteps 1.5.0
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.2.1
		puzzle-base: Puzzle Base 1.2.1
		puzzle-gui: Puzzle GUI 1.2.1
		puzzle-models: Puzzle Models 1.2.1
		puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		puzzleslib: Puzzles Lib 3.3.1
		quartzelv: Quartz Elevator 2.1.1+1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 4.0.2+1.18.2
		roughlyenoughitems: Roughly Enough Items 8.0.442
		rpg-hud: RPG-Hud 3.9.2
		rpgdifficulty: Rpg Difficulty 1.0.11
		rpgstats: RPGStats 4.3.8+1.18.2
		runelic: Runelic 11.0.1
		satin: Satin 1.7.0
		seedfix: Seed Fix 1.0.1
		server_translations_api: Server Translations API 1.4.10+1.18.2
		sit: Sit 1.18.2-18
		skinlayers: 3d Skin Layers 1.4.2-mc1.18.2
		sodium: Sodium 0.4.1+build.15
		spark: spark 1.8.14
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.3.0
		stacker: Stacker 2.1.3
		starterkit-fabric: Starter Kit (Fabric) 3.1
		styled-nicknames: Styled Nicknames 1.0.4+1.18
		styledchat: Styled Chat 1.2.3+1.18
		terrablender: TerraBlender 1.1.0.94
		the_bumblezone: The Bumblezone - Fabric 5.0.8+1.18.2
		things: Things 0.2.16+1.18
		tlcosmetica: Cosmetica 0.4.0
		toms_storage: Tom's Simple Storage Mod 1.3.0
		tooltiprareness: Tooltip Rareness 1.0.3
		tradingpost: Trading Post 3.2.0
		trashslot: TrashSlot 11.0.2
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		tweed4_annotated: tweed4_annotated 1.3.0
		tweed4_base: tweed4_base 1.4.2+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.1+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.0+mc1.18.2
		universalbonemeal: Universal Bone Meal 3.0.2
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.12-1.18.2
		villager-hats: Villager Hats Mod 1.3.1
		villagernames: Villager Names 4.0.3
		visuality: Visuality 0.4.2
		visualworkbench: Visual Workbench 3.2.0
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		voidz: VoidZ 1.0.6
		wandering_collector: Wandering Collector 1.1.1+mc1.18.2
		waystones: Waystones 2.5.0
		wi_zoom: WI Zoom 1.3-MC1.18.2
		windchimes: Windchimes 1.2.0
		wthit: wthit 4.8.0
		xaerominimap: Xaero's Minimap 22.3.1.1
		xaeroworldmap: Xaero's World Map 1.20.4.1
		xps: Xp Obelisk 0.3.4.r_for_1.18.2_Fabric
		yigd: You're in Grave Danger 1.3.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.7
	Loaded Shaderpack: ComplementaryShaders_v4.3.3_-a-_Extreme_-_Compatibility.zip
		Profile: Custom (+23 options changed by user)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.15, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 4
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Excalibur_V1.18.zip, file/Fabric_Friendly_Excalibur_1.18.2_v1.0.zip, file/Excalibur_Mod_Support_V1.18.1.1.zip, file/Caliburn_Variations_v1.0_-_1.18.zip, file/Caliburn_Leaves_v2.1_-_1.18.zip, file/Wooden Door Sounds.zip (incompatible), file/STONEBORN - 1.18 - V3.1.zip, file/STONEBORN - 1.18 - EXTENDED V1.3.zip, file/EmbellishedStone-1.18-1.0.0.zip, file/Mizunos 16 Craft JE CIT_1.18.1-1.0.zip, file/EclecticTrove-1.18-1.0.1.zip, file/Invisible Item Frame Pack_1.18.1-1.0.zip, file/Xaero's Minimap - Mod Icons.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/8364747/latest.log)

**Comment by CorgiTaco** [comment]
pehkui: Pehkui 3.2.0+1.14.4-1.19

Downgrade this mod^
