### ISSUE TITLE
[Crash]: Generating new chunk- firecracker shrubland

### ISSUE THREAD

**Issue by Lozf** [CorgiTaco/BYG#701]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2-1.4-RC-7

### Terrablender

1.1.0.99

### Mod Loader

Fabric

### Mod Loader Version

13.3

### What happened?

When running through a forest it started to generate a new chunk and then crashed.  This crash happens very infrequently, and I've been running around in many different worlds.  Since it's been so infrequent- like twice in 100 worlds- I haven't been able to reproduce yet by isolating the mod, so I can't be sure if it is incompatibility or not.  Also if it's not byg causing it, I apologize for posting here!

### crash-log

https://gist.github.com/Lozf/26409e8e4e2bce42f4fb1cefc7334416

### latest.log

https://gist.github.com/Lozf/d471d5fcb64ee290160d503a4659bcd8

**Comment by Lozf** [comment]
Ran into the crash again- with about half as many mods.  I attempted to do a bisect search but so far have been unable to reproduce to figure out if it is mod compatibility.  https://gist.github.com/Lozf/303d78926e2fb712bc48b0fe1ff4ba45

**Comment by milay** [comment]
Had the same crash, chunk generation error involving the firecracker shrubland


---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/3/22, 10:00 PM
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / byg:firecracker_shrubland]=net.minecraft.class_1959@2204937}]
	at net.minecraft.class_1966.method_39525(class_1966.java:136)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.lambda$finalizeWorldGen$4(BiomeModificationImpl.java:173)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_1966.method_38115(class_1966.java:258)
	at net.minecraft.class_2794.method_12102(class_2794.java:401)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md67ba8e$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1966.method_39525(class_1966.java:136)
	at net.fabricmc.fabric.impl.biome.modification.BiomeModificationImpl.lambda$finalizeWorldGen$4(BiomeModificationImpl.java:173)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_1966.method_38115(class_1966.java:258)
	at net.minecraft.class_2794.method_12102(class_2794.java:401)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md67ba8e$lambda$injectLightmapSetup$1$4(class_2806.java:546)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Chunk to be generated --
Details:
	Location: -84,110
	Position hash: 476741369772
	Generator: net.minecraft.class_3754@64a9555e
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_3222['rootyful'/366820, l='ServerLevel[Paradise]', x=-1122.32, y=70.00, z=1557.79]]
	Chunk stats: 5451
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,118,32), Section: (at 0,6,0 in -2,7,2; chunk contains blocks -32,-64,32 to -17,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 4983252 game time, 7355662 day time
	Level name: Paradise
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 40312 (now: false), thunder time: 85922 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:910)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3358449176 bytes (3202 MiB) / 7189037056 bytes (6856 MiB) up to 9294577664 bytes (8864 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24242.04
	Virtual memory used (MB): 20839.97
	Swap memory total (MB): 7902.41
	Swap memory used (MB): 926.16
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8864m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 3.0.0
		additionalstructures: Additional Structures 3.0.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.10
		aqupdcaracal: Caracal mob 1.18.2-1.3.8
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architects_palette: Architect's Palette Fabric 1.7
		architectury: Architectury 4.1.36
		attributefix: AttributeFix 14.0.1
		autoconfig1u: Auto Config v1 Updated 3.4.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 3.0.0+0
		basicshields: Basic Shields [Fabric] 1.3.1-1.18.2
		bcc: BetterCompatibilityChecker fabric-1.0.5
		beehivetooltips: Beehive Tooltips 1.4.2
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.0
		betterf3: BetterF3 1.2.4
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.0
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.0
		betterthirdperson: Better Third Person 1.7.2
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		biomeinfo: BiomeInfo 1.18.2-10
		biomemakeover: Biome Makeover 1.18.2-1.4.15
		blockus: Blockus 2.4.3+1.18.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bookshelf: Bookshelf 13.0.7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.6-1.18.2
		byg: Oh The Biomes You'll Go 1.4-RC-7
		capybara: Capybara 1.0.3
		cardinal-components: Cardinal Components API 4.1.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.1.4
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.1.4
		cardinal-components-level: Cardinal Components API (world saves) 4.1.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		carrier: Carrier 1.10.0
		ce: Cave Enhancements 1.0.4
		charm: Charm 4.0.0
		charmonium: Charmonium 4.0.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chunkcopy: Chunk Copy 2.0.0
		cleardespawn: Clear Despawn 1.1.7
		clienttweaks: Client Tweaks 7.1.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		clumps: Clumps 8.0.0+7
		coat: Coat 1.0.0-beta.17+mc1.18.2
		collective-fabric: Collective (Fabric) 4.26
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.1.2-1.18.2
		companion: Companion 2.0.0
		consistency_plus: Consistency Plus 0.5.0-RC2+1.18.2
		continuity: Continuity 1.1.0+1.18.2
		controlling: Controlling For Fabric 9.0+17
		craftingtweaks: Crafting Tweaks 13.0.0
		crawl: Crawl 0.10.2
		creatures_of_the_jungle: Creatures From The Jungle 1.0.0
		creeperoverhaul: Creeper Overhaul 1.3.0
		croptopia: Croptopia 1.8.3
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		darkpaintings: DarkPaintings 10.0.1
		dashloader: DashLoader 3.1.1+1.18
		dawn: Dawn API 3.3.0
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.2
		deleteworldstotrash: Delete Worlds To Trash 3.2.0
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disenchanter: Disenchanter 0.1.5+1.18
		dragonloot: DragonLoot 1.0.10
		drippyloadingscreen: Drippy Loading Screen 1.5.1
		duckling: Duckling 1.0.2
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.1.0
		earthbounds: Earthbounds 1.0.5c
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easymagic: Easy Magic 3.3.0
		easyshulkerboxes: Easy Shulker Boxes 3.1.1
		eatinganimationid: Eating Animation 1.5
		ecologics: Ecologics 1.4.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchantment_lore: Enchantment Lore 1.2.6-1
		enchdesc: EnchantmentDescriptions 10.0.2
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		entityculling: EntityCulling-Fabric 1.5.0
		equipmentcompare: Equipment Compare 1.2.12
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.13.3
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		fallingtree: FallingTree 3.4.1
		fancymenu: FancyMenu 2.6.4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.0
		fiber: fiber 0.23.0-2
		floral_flair: Floral Flair 1.3.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.3.0
		geckolib3: Geckolib 3.0.35
		geodes: More Geodes 1.3-SNAPSHOT.1
		goblintraders: Goblin Traders 1.5.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.7
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.11
		gud_recipe_confidence: Recipe Confidence 1.0.2
		highlighter: Highlighter 1.1.2
		horseinfo: Horse Info 0.4.1-1.18
		iceberg: Iceberg 1.0.38
		ikwid_fabric: I know what I'm doing! [FABRIC] 1.1+1.18.x
		illagerexp: Illager_Expansion 0.1.3
		immersive_weathering: Immersive Weathering 2.3.2
		incantationem: Incantationem 1.1.3+1.18.2
		incubus_core: Incubus Core 1.6.6+1.18.2
		indium: Indium 1.0.2+mc1.18.2
		inmis: Inmis 2.5.2-1.18.2
		inventoryhud: Inventory HUD + 3.4.2
		invmove: InvMove 0.6.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.2-build.32
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		lovely_snails: Lovely Snails 1.0.4+1.18
		maelstrom_library: Maelstrom Library 1.2.4-1.18.2
		magnumtorch: Magnum Torch 3.1.2
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-more-data: Maybe More Data 1.0.0-1.18.2
		mcwfences: Macaw's Fences and Walls 1.0.0
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwtrpdoors: Macaw's Trapdoors 1.0.5
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.20
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		mobscarecrow: Mob Scarecrow 1.2.2
		modid: Creatures Of The Snow 1.0.0
		modmenu: Mod Menu 3.1.0
		moreachievements: MoreAchievements 1.0.8
		moretags: More Tags 3.0.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.22
		multipart_entities: MultipartEntities 1.1.5-1.18.2
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.2
		notenoughanimations: NotEnoughAnimations 1.5.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		orcinus: Hedgehog 1.18.2-1.0.0
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		overweight_farming: Overweight Farming 1.18.2-1.1.0-fabric
		oxidized: Oxidized 1.6.3
		patchouli: Patchouli 1.18.2-66-FABRIC
		paxi: Paxi 1.18.2-Fabric-2.0
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
		pigsteel: Pigsteel Mod 1.7.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player-data-api: Player Data API 0.1.0+1.18
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.0.20-1.18.2
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.2.1
		puzzle-base: Puzzle Base 1.2.1
		puzzle-gui: Puzzle GUI 1.2.1
		puzzle-models: Puzzle Models 1.2.1
		puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		puzzleslib: Puzzles Lib 3.3.1
		quartzelv: Quartz Elevator 2.1.1+1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 4.0.2+1.18.2
		rightclickharvest: Right Click Harvest 1.5.1
		roughlyenoughitems: Roughly Enough Items 8.0.442
		roughlyenoughprofessions: Roughly Enough Professions 1.0.0
		runelic: Runelic 11.0.1
		satin: Satin 1.7.2
		sbm-jukebox: SBM-Jukebox 1.0.2
		sentimentality3: Sentimentality 3 1.4.12
		simple-rpc: Simple Rpc 2.7.3
		skinlayers: 3d Skin Layers 1.4.2-mc1.18.2
		skylorlib: SkyLib 1.2.3
		sodium: Sodium 0.4.1+build.15
		spark: spark 1.8.14
		spirit: Spirit 1.2.1
		spruceui: SpruceUI 3.3.0+1.17
		starterkit-fabric: Starter Kit (Fabric) 3.1
		stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		styled-nicknames: Styled Nicknames 1.0.4+1.18
		styledchat: Styled Chat 1.2.3+1.18
		terrablender: TerraBlender 1.1.0.98
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		the_aether: Paradise Lost 1.6.8+1.18.2
		the_bumblezone: The Bumblezone - Fabric 5.0.9+1.18.2
		thonkutil: ThonkUtil 2.12.0+1.18
		thonkutil-base: ThonkUtil Base 1.12.0+93f5607360
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.1+974d16dd60
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.18+4c66479160
		thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.13+4c66479160
		thonkutil-legacy: ThonkUtil Legacy 1.0.19+aa74e18060
		thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.11+4c66479160
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.0+6d0d59d760
		thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.8+4c66479160
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.19+4c66479160
		tlcosmetica: Cosmetica 0.4.0
		toms_storage: Tom's Simple Storage Mod 1.3.0
		tradingpost: Trading Post 3.2.0
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		tweed4_annotated: tweed4_annotated 1.3.0
		tweed4_base: tweed4_base 1.5.0+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		twigs: Twigs 1.1.3+legacy.1.18.2
		universal_ores: Universal Ores 1.2.1
		universalbonemeal: Universal Bone Meal 3.0.2
		unstructured: Unstructured 0.3.1+1.18.2
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.12-1.18.2
		villager-hats: Villager Hats Mod 1.3.1
		villagernames: Villager Names 4.0.3
		visuality: Visuality 0.4.2
		visualworkbench: Visual Workbench 3.2.0
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		voidz: VoidZ 1.0.6
		wandering_collector: Wandering Collector 1.1.2+mc1.18.2
		waystones: Waystones 2.5.0
		windchimes: Windchimes 1.2.0
		witherturnsskeletons: Wither turns Skeletons 1.2.0-1.18.2
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.8.0
		xaerominimap: Xaero's Minimap 22.4.0
		xaeroworldmap: Xaero's World Map 1.20.5
		yigd: You're in Grave Danger 1.3.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.7
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.0
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Loaded Shaderpack: ComplementaryShaders_v4.1.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['rootyful'/366820, l='ServerLevel[Paradise]', x=-1122.32, y=70.00, z=1557.79]]
	Data Packs: vanilla, Fabric Mods, file/VanillaTweaks_c996620.zip, file/armor statues v2.8.3.zip, file/cauldron concrete v2.0.5.zip, file/count mob deaths v1.1.2.zip, file/custom nether portals v2.3.5.zip, file/double shulker shells v1.3.2.zip, file/dragon drops v1.3.2.zip, file/durability ping v1.1.2.zip, file/more mob heads v2.9.4.zip, file/nether portal coords v1.1.2.zip, file/real time clock v1.1.2.zip, file/silence mobs v1.1.2.zip, file/track raw statistics v1.5.2.zip, file/track statistics v1.1.3.zip, file/unlock all recipes v2.0.3.zip, file/villager workstation highlights v1.1.2.zip, file/wandering trades v1.5.1.zip, file/Budding.Blocks.Silktouchable.zip, Repurposed_Structures-Friends_And_Foes-v1.zip, Repurposed_Structures-More_Villagers_v5.zip
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by CorgiTaco** [comment]
this is more than likely a conflict with another biome adding mod

**Comment by milay** [comment]
I wouldn't be surprised, but is that something that can be avoided/fixed?

**Comment by CorgiTaco** [comment]
you need to take the mods out that add any world generation features and add them back 1 by 1

**Comment by Lozf** [comment]
Hey Milay- I looked through our mods and here are the ones we have in common-maybe with this we can both test and figure out which one!
architects palette
architectury
balm
better animals plus
blockus
oh the biomes you'll go
charm
cloth config
collective
creatures of the jungle
dawn
ecologies
fabric API
fabric language kotlin
falling leaves
geckolib
patchouli
sodium
terrablender
trinkets

Although creatures from the jungle- I'm assuming got renamed to creatures from the warmth- from the same mod group as creatures from the snow and ecologies?

**Comment by Lozf** [comment]
It's ecologics!  I'll be testing the other two mods by the same developers to see if those have the same conflicts as well.  https://gist.github.com/Lozf/9c96eeb0364289c31eec270f66c1d553

https://www.curseforge.com/minecraft/mc-mods/ecologics

**Comment by CorgiTaco** [comment]
Use Cyanide and send your latest.logs: 

Fabric: https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric
Forge: https://www.curseforge.com/minecraft/mc-mods/cyanide-forge

**Comment by CorgiTaco** [comment]
Closing due to inactivity
