### ISSUE TITLE
[Crash]: Rendering Overlay

### ISSUE THREAD

**Issue by Sarriaman** [CorgiTaco/BYG#726]
### Minecraft Version

1.18.2

### BYG Versions

1.18.2 RC-10 

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

When i play with the mods mekanism 1.18.2, JEI and alex mobs everything is fine but when i add BYG the game crashes (i tried removing optifine still doesnt works, tried executing individually byg and optifine it works) so i dont know what it is

### crash-log

https://gist.github.com/Sarriaman/61b3cb38be193b4aa10ddcfe8204e116

### latest.log

https://gist.github.com/Sarriaman/c10d10780c3609766c8f87324b1119db

**Comment by CorgiTaco** [comment]
update JEI
```
n: Mod �emekanism�r only supports �3jei�r �o9.7.0.180 or above�r
�7Currently, �3jei�r�7 is �o9.5.5.174
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:50) ~[fmlcore-1.18.2-40.1.0.jar%2363!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
```
