### ISSUE TITLE
[Crash]: game crashes when I eat (mod incompatibiliy)

### ISSUE THREAD

**Issue by CsillaAria** [CorgiTaco/BYG#751]
### Minecraft Version

1.18.2

### BYG Versions

1.4-RC-11

### Terrablender

1.1.0.99

### Mod Loader

Forge

### Mod Loader Version

40.1.19

### What happened?

whenever I eat an apple in survival the game crashes, I haven't tried other foods I don't know if it would make a difference. The mod works fine on its own so it has to be a compatibility issue with another mod. If it helps here is a pic of the error message:
![IMG_0239](https://user-images.githubusercontent.com/77200112/167742435-726a8779-51d8-4697-a3a0-a1c21dd37851.JPG)

### crash-log

https://gist.github.com/CsillaAria/172ca6710ed3a52c6e7b8ba29dc3cfe6

### latest.log

https://gist.github.com/CsillaAria/172ca6710ed3a52c6e7b8ba29dc3cfe6

**Comment by CsillaAria** [comment]
I had time, so I removed all mods except Terrablender, and BYG, and started a new world. I added each mod I had been using one at a time, and tested tried eating every time, even after adding all the mods I had been using back no crash happened when eating.
Returning to my previous world and eating however still caused the crash to happen. Next I'm going to remove mods in the world that keeps crashing one at a time, and see if that has an effect. It's getting late here though, so that will have to wait till tomorrow.

**Comment by CorgiTaco** [comment]
This is another mod's issue entirely unrelated to byg: 

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.advancements.Advancement.m_138325_()" because "p_135986_" is null
	at net.minecraft.server.PlayerAdvancements.m_135985_(PlayerAdvancements.java:379) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at net.minecraft.server.PlayerAdvancements.m_135996_(PlayerAdvancements.java:372) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:PlayerAdvancementsMixin,pl:mixin:A}
	at glitchy_mc.ms2.procedures.UndergroundRewardProcedure.execute(UndergroundRewardProcedure.java:36) ~[MoreStones+II+v1.50.1+(1.18.2).jar%2370!/:?] {re:classloading}
```
Issue is caused by: https://www.curseforge.com/minecraft/mc-mods/more-stones-ii

**Comment by CsillaAria** [comment]
Thank you so much! I will inform them about this.
