### ISSUE TITLE
[Crash]: Crash on worldload with *any* custom datapack

### ISSUE THREAD

**Issue by Tralomine** [CorgiTaco/BYG#801]
### Minecraft Version

1.18.2

### BYG Version

1.4

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.48

### What happened?

when loading any datapack on world creation, a crash happen, even if the datapack is empty and has for only file a pack.mcmeta

this does not happen if just byg is removed an the datapacks load just fine with just forge and terrablender

### crash-log

https://gist.github.com/Tralomine/c1d3b50138966929f75d2fbc750e6da8

### latest.log

https://gist.github.com/Tralomine/3edd70b111ecb89a15f81ee084146e75

**Comment by CorgiTaco** [comment]
@Tralomine could you upload a video of how to recreate this? Bc I tried and failed to recreate the issue

**Comment by Tralomine** [comment]
https://youtu.be/gLHd8yotVfE

**Comment by egelja** [comment]
I'm having the same issue, except without any datapacks

[crash-2022-06-08_10.17.31-client.txt](https://github.com/AOCAWOL/BYG/files/8863005/crash-2022-06-08_10.17.31-client.txt)

**Comment by jdw-mis** [comment]
Confirmed with a blank datapack on Fabric.
[crash-2022-06-08_13.59.25-server.txt](https://github.com/AOCAWOL/BYG/files/8865019/crash-2022-06-08_13.59.25-server.txt)
Also tried with Towers of the Wild Reworked, which is a known good datapack.
[crash-2022-06-08_14.07.01-server.txt](https://github.com/AOCAWOL/BYG/files/8865030/crash-2022-06-08_14.07.01-server.txt)

**Comment by jdw-mis** [comment]
On further testing this issue was introduced with TerraBlender 1.1.0.100, 99 works fine.

**Comment by Amagous** [comment]
I just came to post that I had a similar although different error, also with BYG and/or TerraBlender, and after several other not-successful fixes, trying jdw-mis's solution worked for me. I "downgraded" from TerraBlender-forge-1.18.2-1.1.0.102.jar to 1.1.0.99.jar, and was finally able to successfully generate a world again. For the moment/current version, if anyone else is having crashes and your error log references BYG (Which requires TerraBlender), try jdw-mis's solution and "downgrade" to 1.1.0.99 of Terrablender if you're running version 100+.

<details>
<summary> Click to expand. Crash Log for posterity. Prominent Error: "java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / byg:basalt_barrera]=net.minecraft.world.level.biome.Biome@7dcdb4de}]"</summary>
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/9/22, 12:46 PM
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / byg:basalt_barrera]=net.minecraft.world.level.biome.Biome@7dcdb4de}]
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at net.minecraft.world.level.biome.BiomeSource.md2ee850$lambda$appendDeferredBiomesList$0$0(BiomeSource.java:1087) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts_forge.mixins.json:DisableVanillaMineshaftsMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:CancelSearchVanillaStrongholdMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:DisableVanillaStrongholdsMixinForge,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at net.minecraft.world.level.biome.BiomeSource.md2ee850$lambda$appendDeferredBiomesList$0$0(BiomeSource.java:1087) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.BiomeSourceAccess,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:byg.mixins.json:access.ChunkGeneratorAccess,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:bettermineshafts_forge.mixins.json:DisableVanillaMineshaftsMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:CancelSearchVanillaStrongholdMixinForge,pl:mixin:APP:betterstrongholds_forge.mixins.json:DisableVanillaStrongholdsMixinForge,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
-- Chunk to be generated --
Details:
	Location: -1,-1
	Position hash: -1
	Generator: net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@6957d316
Stacktrace:
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2333!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:camera.ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23154!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
</details>

**Comment by sojke** [comment]
I've had the same crash as @Amagous with BYG fabric 1.4 and terrablender fabric 1.1.0.102, while using a structure datapack. I've noticed disabling the 'basalt barrera' biome works as well instead of downgrading. I'm also using structure datapacks in mod format (CTOV for example) and with those it works just fine. I'm gonna test if I can convert a datapack to a mod myself and if the crash then still occurs.
[crash-2022-06-15_15.17.09-server.txt](https://github.com/AOCAWOL/BYG/files/8909740/crash-2022-06-15_15.17.09-server.txt)

**Comment by NobleDraconian** [comment]
Same thing here - was having issues with BYG & Immersive portals' "dimension stack" feature. I downgraded terrablender from 102 to 99, crash stopped occurring.

**Comment by Shadowex3** [comment]
So I didn't have any datapacks and tried downgrading terrablender, I still got this crash. Running with cyanide gave a little more detail, but nothing too helpful since there didn't seem to be any other mods mentioned. It was always either minecraft's seagrass or sea cucumber.

I have no idea how I eventually fixed it, the only thing I can think of is I wiped out a bunch of config files completely. I also downloaded an unofficial fix for rubidium extras that may have fixed a parallel issue.

```
Cycle:
At step 9
Feature 'minecraft:seagrass_simple'
  must be before 'minecraft:kelp_cold' (defined in 'minecraft:cold_ocean' at index 9, 10 and 3 others)
  must be before 'minecraft:seagrass_warm' (defined in 'minecraft:dark_forest' at index 21, 22 and 1 others)
  must be before 'minecraft:sea_pickle' (defined in 'byg:lush_stacks' at index 9, 10 and 3 others)
  must be before 'minecraft:seagrass_normal' (defined in 'byg:lush_stacks' at index 10, 11)
  must be before 'minecraft:seagrass_simple' (defined in 'minecraft:ocean' at index 8, 9)
```

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the latest versions of all mods relating to world generation.
