### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by VoQZHD** [CorgiTaco/BYG#820]
### Minecraft Version

1.18.2

### BYG Version

1.4.1

### Terrablender Version

1.1.0.102

### Mod Loader

Fabric

### Mod Loader Version

fabric-api-0.56.0

### What happened?

[02:34:40] [Render thread/INFO]: Initializing ClientSide Packet Registries
[02:35:06] [Render thread/INFO]: JourneyMap log initialized.
[02:35:06] [Render thread/INFO]: initialize ENTER
[02:35:06] [Render thread/WARN]: Already initialized, aborting
[02:35:29] [Render thread/INFO]: Preloaded theme textures: 73
[02:35:29] [Render thread/INFO]: postInitialize EXIT, elapsed count 1 avg 225.49ms
[02:35:37] [Render thread/WARN]: Tried to register resource reload listener jei:lifecycle twice!
[02:35:39] [Render thread/WARN]: Attempted to fire BYG after registries froze a 2nd time...
java.lang.Throwable
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at potionstudios.byg.BYGFabric.afterRegistriesFreeze(BYGFabric.java:59)
	at net.minecraft.util.registry.Registry.handler$bba000$byg_afterRegistriesFreeze(Registry:1084)
	at net.minecraft.util.registry.Registry.freezeRegistries(Registry:371)
	at net.minecraft.client.MinecraftClient.handler$cfi001$onStart(MinecraftClient:10985)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:716)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dng000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:19510)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:759)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

[02:35:42] [Render thread/INFO]: "Oh The Biomes You'll Go" after registries freeze event firing...
[02:35:42] [Render thread/INFO]: BYG: "Common Setup" Event Complete!
[02:35:42] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Block{byg:foragers_table} is defined in too many tags
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.world.poi.PointOfInterestType.method_20355(PointOfInterestType:135)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.world.poi.PointOfInterestType.setup(PointOfInterestType:132)
	at net.minecraft.world.poi.PointOfInterestType.byg_invokeRegisterBlockStates_$md$3ba613$3(PointOfInterestType)
	at potionstudios.byg.mixin.access.PoiTypeAccess.byg_invokeRegisterBlockStates(PoiTypeAccess.java)
	at potionstudios.byg.BYG.commonLoad(BYG.java:60)
	at potionstudios.byg.BYGFabric.afterRegistriesFreeze(BYGFabric.java:65)
	at net.minecraft.util.registry.Registry.handler$bba000$byg_afterRegistriesFreeze(Registry:1084)
	at net.minecraft.util.registry.Registry.freezeRegistries(Registry:371)
	at net.minecraft.client.MinecraftClient.handler$cfi001$onStart(MinecraftClient:10985)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:716)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dng000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:19510)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:759)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### crash-log

https://gist.github.com/VoQZHD/fc9ded11a45b437cd883689b4aea36fd

### latest.log

https://gist.github.com/VoQZHD/e8a98cfc014c92284cf63f9afa347982

### Did you isolate BYG?

I did not try BYG alone

**Comment by MScott7** [comment]
I think I'm also having this issue, seeing "Attempted to fire BYG after registries froze a 2nd time..." and "Block{byg:foragers_table} is defined in too many tags". 

Using Minecraft 1.18.2, fabric 0.14.8, fabric-api 0.56.1, terrablender 1.1.0.99, BYG 1.4.1. 

latest.log: https://gist.github.com/MScott7/44aa4740745bb8ebe2fcdf2504c261f3
crash report: https://gist.github.com/MScott7/93ee63a2c7bd9561fe84b0cd4b92acb2

Hope this helps

**Comment by Bullseye55** [comment]
Getting this exact same crash on the 1.19 version as well. Unsure the cause.

Edit: This seems to be the result of another crash from various other mods. A cascade result. Removing a newer mod that caused a crash, and this fully resolved.

**Comment by CorgiTaco** [comment]
I'm going to go by what Bullseye said, this could be a simple case of BYG being wrongfully blamed. Make sure to use the latest versions for all your mods!
