### ISSUE TITLE
[Crash]: Crash to desktop when creating a new singleplayer world

### ISSUE THREAD

**Issue by Gamemassa** [CorgiTaco/BYG#849]
### Minecraft Version

1.19

### BYG Version

2.0.0.6

### Terrablender Version

2.0.0.120

### Mod Loader

Forge

### Mod Loader Version

41.0.98

### What happened?

I tried to create a new singleplayer world and my game crashed to desktop. Crash report contains the following error message:

-- Head --
Thread: Render thread
Stacktrace:
	at potionstudios.byg.BYGForgeEventsHandler.registerCommands(BYGForgeEventsHandler.java:63) ~[Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.6.jar%23190!/:2.0.0.6] {re:classloading,pl:epic_rei_lmao:B}
	at potionstudios.byg.__BYGForgeEventsHandler_registerCommands_RegisterCommandsEvent.invoke(.dynamic) ~[Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.6.jar%23190!/:2.0.0.6] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}

### crash-log

[crash-2022-07-12_15.54.31-client.txt](https://github.com/AOCAWOL/BYG/files/9096407/crash-2022-07-12_15.54.31-client.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9096409/latest.log)

### Did you isolate BYG?

I tried BYG alone

**Comment by Gamemassa** [comment]
Whatever was causing this issue appears to be fixed with BYG 2.0.0.7 but I'm going to keep the thread open for a bit longer just in case.

**Comment by CorgiTaco** [comment]
This should no longer be an issue when using 1.19.2 versions of BYG & Forge
