### ISSUE TITLE
[Crash]: Incompatibility with Wythers' Overhauled World?

### ISSUE THREAD

**Issue by Lozf** [CorgiTaco/BYG#854]
### Minecraft Version

1.19

### BYG Version

1.19-2.0.0.7

### Terrablender Version

1.19-2.0.0.117

### Mod Loader

Fabric

### Mod Loader Version

14.8

### What happened?

Crashes on creating a new world, both byg and William wythers overhauled world mod show up.  Using whyther's wwoo-2.2+1.19.jar version.  https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld/files/3868257 .

### crash-log

[crash-2022-07-13_22.48.12-server.txt](https://github.com/AOCAWOL/BYG/files/9108948/crash-2022-07-13_22.48.12-server.txt)

### latest.log

[latest.log](https://github.com/AOCAWOL/BYG/files/9108949/latest.log)

### Did you isolate BYG?

I did not try BYG alone

**Comment by CorgiTaco** [comment]
This should no longer be an issue, if you still get this crash please comment/reopen this issue. Ensure you're using the ***latest*** versions of all mods relating to world generation.

**Comment by dmkenza** [comment]
I see problem with the last version.

Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

```
Cycle:
At step 9
Feature 'minecraft:patch_grass_savanna'
must be before 'minecraft:patch_grass_taiga_2' (defined in 'byg:maple_taiga' at index 2, 3)
must be before 'minecraft:brown_mushroom_taiga' (defined in 'byg:shattered_glacier' at index 3, 4 and 8 others)
must be before 'minecraft:red_mushroom_taiga' (defined in 'minecraft:mushroom_fields' at index 2, 3 and 14 others)
must be before 'minecraft:patch_grass_savanna' (defined in 'wythers:cold_island' at index 4, 5)

at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141)
at net.minecraft.class_7510.handler$bmf000$buildFeaturesPerStepWithAdvancedCycleDetection(class_7510.java:529)
at net.minecraft.class_7510.method_44210(class_7510.java)
at net.minecraft.class_2794.method_44215(class_2794.java:136)
at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
at net.minecraft.class_2794.method_12102(class_2794.java:397)
at net.minecraft.class_2806.method_20613(class_2806.java:145)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:679)
... 14 more
```



Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.0
causes the problem for now. 

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7 
The previous one dosnt cause.
