### ISSUE TITLE
[Crash]: Crash at startup

### ISSUE THREAD

**Issue by lumen211** [CorgiTaco/BYG#891]
### Minecraft Version

1.18.2

### BYG Version

1.4.2

### Terrablender Version

1.1.0.102

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### What happened?

Without byg,the game starts normally,but when i tried to start with byg it crashes and only works when byg is not present.

### crash-log

[crash.txt](https://github.com/AOCAWOL/BYG/files/9264160/crash.txt)

### latest.log

Picked up _JAVA_OPTIONS: 
2022-08-04 18:46:21,235 main WARN Advanced terminal features are not available in this environment
[18:46:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Lumen20, --version, 1.18.2-forge-40.1.68, --gameDir, C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game, --assetsDir, C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game\assets, --assetIndex, 1.18, --uuid, 9f51bbc9179a428d9d135196f9d2d22c, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, , --xuid, , --userType, mojang, --versionType, release, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.68, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[18:46:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[18:46:22] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/lucia/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[18:46:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\net\minecraftforge\fmlcore\1.18.2-40.1.68\fmlcore-1.18.2-40.1.68.jar is missing mods.toml file
[18:46:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.1.68\javafmllanguage-1.18.2-40.1.68.jar is missing mods.toml file
[18:46:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.1.68\lowcodelanguage-1.18.2-40.1.68.jar is missing mods.toml file
[18:46:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\lucia\AppData\Roaming\.tlauncher\legacy\Minecraft\game\libraries\net\minecraftforge\mclanguage\1.18.2-40.1.68\mclanguage-1.18.2-40.1.68.jar is missing mods.toml file
[18:46:26] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.module.ResolutionException: Modules terralith and amplifiednether export package __MACOSX.net.hypercubemc.seedfix to module bettershields
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
Buy the game, pirated versions of MC are bound to break and we will not provide support for those pirating MC
