### ISSUE TITLE
[Crash]:  Crashes after disabling biomepedia

### ISSUE THREAD

**Issue by 3dguru** [CorgiTaco/BYG#903]
### Minecraft Version

1.19

### BYG Version

2.0.0.7

### Terrablender Version

2.0.1.125

### Mod Loader

Fabric

### Mod Loader Version

0.14.9

### What happened?

disabled bimoepedia with in the client config folder, crashes and will not load if it is set to false 

### crash-log

	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at potionstudios.byg.BYG.commonLoad(BYG.java:51) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7.jar:?]
	at potionstudios.byg.BYGFabric.afterRegistriesFreeze(BYGFabric.java:65) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7.jar:?]
	at net.minecraft.util.registry.Registry.handler$bcn000$byg_afterRegistriesFreeze(Registry:1127) ~[?:?]
	at net.minecraft.util.registry.Registry.freezeRegistries(Registry:406) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$dbh001$onStart(MinecraftClient:15986) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[21:47:54] [Render thread/INFO]: Stopping!
[21:47:54] [Render thread/WARN]: getErrorETFTexture() was called, investigate this if called too much
[21:47:54] [Render thread/INFO]: emissive suffixes loaded: {_e}
[21:47:54] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.texture.TextureManager.close(TextureManager:173) ~[?:?]
	at net.minecraft.client.MinecraftClient.close(MinecraftClient:1092) ~[?:?]
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient:1068) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Process exited with code 0.

### latest.log

	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at potionstudios.byg.BYG.commonLoad(BYG.java:51) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7.jar:?]
	at potionstudios.byg.BYGFabric.afterRegistriesFreeze(BYGFabric.java:65) ~[Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.7.jar:?]
	at net.minecraft.util.registry.Registry.handler$bcn000$byg_afterRegistriesFreeze(Registry:1127) ~[?:?]
	at net.minecraft.util.registry.Registry.freezeRegistries(Registry:406) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$dbh001$onStart(MinecraftClient:15986) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
[21:47:54] [Render thread/INFO]: Stopping!
[21:47:54] [Render thread/WARN]: getErrorETFTexture() was called, investigate this if called too much
[21:47:54] [Render thread/INFO]: emissive suffixes loaded: {_e}
[21:47:54] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.texture.TextureManager.close(TextureManager:173) ~[?:?]
	at net.minecraft.client.MinecraftClient.close(MinecraftClient:1092) ~[?:?]
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient:1068) ~[?:?]
	at net.minecraft.client.main.Main.method_44604(Main:260) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Process exited with code 0.

### Did you isolate BYG?

I tried BYG alone

**Comment by CorgiTaco** [comment]
I cannot recreate this crash on 1.19.2.
