### ISSUE TITLE
[Bug]: Couldn't load structure byg:village/red_rock/houses/red_rock_cleric

### ISSUE THREAD

**Issue by magneticflux-** [CorgiTaco/BYG#932]
### Minecraft Version

1.19.2

### BYG Version

2.0.0.8

### Terrablender Version

4.1.1

### Mod Loader

Quilt

### Mod Loader Version

0.17.3

### Bug Severity

Major

### What happened?

```
[22:55:39] [C2ME worker #6/ERROR]: Couldn't load structure byg:village/red_rock/houses/red_rock_cleric
net.minecraft.class_148: Loading NBT data
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2) ~[?:?]
	at net.minecraft.nbt.NbtCompound.read(NbtCompound:495) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:71) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:57) ~[?:?]
	at net.minecraft.nbt.NbtList$1.read(NbtList:43) ~[?:?]
	at net.minecraft.nbt.NbtList$1.read(NbtList:26) ~[?:?]
	at net.minecraft.nbt.NbtCompound.read(NbtCompound:489) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:71) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:57) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo:147) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo:91) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo:36) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.readTemplate(StructureTemplateManager:222) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.loadTemplate(StructureTemplateManager:212) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.loadTemplateFromResource(StructureTemplateManager:124) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.loadTemplate(StructureTemplateManager:102) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.getTemplate(StructureTemplateManager:92) ~[?:?]
	at net.minecraft.structure.StructureTemplateManager.getTemplateOrBlank(StructureTemplateManager:80) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.structure.pool.SinglePoolElement.getStructure(SinglePoolElement:85) ~[?:?]
	at net.minecraft.structure.pool.SinglePoolElement.getBoundingBox(SinglePoolElement:118) ~[?:?]
	at net.minecraft.structure.pool.StructurePool.method_19310(StructurePool:122) ~[?:?]
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at it.unimi.dsi.fastutil.objects.ObjectArrayList$Spliterator.forEachRemaining(ObjectArrayList.java:982) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:520) ~[?:?]
	at java.util.stream.IntPipeline.max(IntPipeline.java:483) ~[?:?]
	at net.minecraft.structure.pool.StructurePool.getHighestY(StructurePool:123) ~[?:?]
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_31114(StructurePoolBasedGenerator:157) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_19305(StructurePoolBasedGenerator:157) ~[?:?]
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?]
	at it.unimi.dsi.fastutil.objects.ObjectArrayList$Spliterator.forEachRemaining(ObjectArrayList.java:982) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:520) ~[?:?]
	at java.util.stream.IntPipeline.max(IntPipeline.java:483) ~[?:?]
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.generatePiece(StructurePoolBasedGenerator:160) ~[?:?]
	at net.minecraft.structure.pool.StructurePoolBasedGenerator.generate(StructurePoolBasedGenerator:355) ~[?:?]
	at net.minecraft.structure.pool.StructurePoolBasedGenerator.method_39824(StructurePoolBasedGenerator:329) ~[?:?]
	at net.minecraft.world.gen.structure.Structure$StructurePosition.method_44021(Structure:116) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.gen.structure.Structure$StructurePosition.generate(Structure:114) ~[?:?]
	at net.minecraft.world.gen.structure.Structure.createStructureStart(Structure:125) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.trySetStructureStart(ChunkGenerator:638) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.method_41041(ChunkGenerator:620) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator:573) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.method_39464(ChunkStatus:59) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.md6692c8$lambda$runGenerationTask$0$5(ChunkStatus:1601) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: java.util.zip.ZipException: Corrupt GZIP trailer
	at java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:225) ~[?:?]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:119) ~[?:?]
	at net.minecraft.util.FixedBufferInputStream.read(FixedBufferInputStream:45) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
	at net.minecraft.nbt.NbtCompound.readString(NbtCompound:484) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:68) ~[?:?]
	at net.minecraft.nbt.NbtCompound$1.read(NbtCompound:57) ~[?:?]
	at net.minecraft.nbt.NbtCompound.read(NbtCompound:489) ~[?:?]
	... 70 more
```

### latest.log

N/A

### Did you isolate BYG?

I did not try BYG alone

**Comment by magneticflux-** [comment]
Trying to open the `red_rock_cleric.nbt` file in Intellij yields:
```
Malformed NBT file:
Unexpected tag id found: 98
```
